-- ================================================================
-- CUVÉE — Produttori lista Lupetti (aggiunta ai 24 già presenti)
-- Eseguire nel SQL Editor di Supabase
-- Zone IDs: Vallée de la Marne = 08daee1e | Montagne de Reims = 49ed27e0 | Côte des Blancs = 91b7c08e
-- ================================================================

INSERT INTO maison (nome, slug, tipo, zona_id, sede_comune, sede_regione, sede_indirizzo, telefono, sito_web, anno_fondazione, proprieta, gruppo, direzione, chef_de_cave, ettari_totali, ettari_proprieta, ettari_gestione, pct_pinot_noir, pct_chardonnay, pct_meunier, certificazioni, tipo_pressa, vinificazione, malolattica, produzione_bottiglie, stock_cantina, importatore_italia, visita_possibile, degustazione_possibile, descrizione, filosofia, fascia_prezzo, is_free) VALUES

-- ── A ──────────────────────────────────────────────────────────

('A. Bergère', 'a-bergere', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Vertus', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Bergère', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 5, 90, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Piccolo vigneron di Vertus, Premier Cru della Côte des Blancs. Produce Blanc de Blancs di netta impronta calcarea e grande freschezza.', 'Espressione autentica del terroir di Vertus attraverso Chardonnay coltivato con rispetto per la vigna.', '€€€', false),

('A. Lamblot', 'a-lamblot', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Villers-sous-Châtillon', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Lamblot', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 20, 30, 50, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron artigianale di Villers-sous-Châtillon nella Valle della Marna. Champagne di carattere con forte identità territoriale.', 'Artigianalità e rispetto per il terroir della Valle della Marna come valori fondanti.', '€€', false),

('Alexandre Bonnet', 'alexandre-bonnet', 'NM', NULL, 'Les Riceys', 'Aube', '138 Rue du Général de Gaulle, 10340 Les Riceys', '+33 3 25 29 30 93', 'www.alexandrebonnet.com', 1946, 'Famille Bonnet', 'Indipendente', NULL, NULL, 40, 40, NULL, 85, 10, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 500000, NULL, NULL, true, true,
 'Maison fondata nel 1946 a Les Riceys nell''Aube. Specializzata in Pinot Noir dell''Aube con Blanc de Noirs di grande struttura e carattere. Les Riceys è anche il comune con tre AOC diverse: Champagne, Rosé des Riceys e Coteaux Champenois.', 'Il Pinot Noir dell''Aube come vocazione: struttura, profondità e un terroir argilloso-calcareo unico che dona ai vini personalità inconfondibile.', '€€€', false),

('Alexandre Flaine', 'alexandre-flaine', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Flaine', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Avize, Grand Cru della Côte des Blancs. Blanc de Blancs di raffinata mineralità gessosa prodotti in piccole quantità.', 'La purezza dello Chardonnay di Avize Grand Cru come unico obiettivo.', '€€€', false),

('Alfred Gratien', 'alfred-gratien', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Épernay', 'Marne', '30 Rue Maurice Cerveaux, 51200 Épernay', '+33 3 26 54 38 20', 'www.alfredgratien.com', 1864, 'Henkell & Co', 'Henkell & Co', 'Nicolas Jaeger', 'Nicolas Jaeger', NULL, NULL, NULL, 30, 35, 35, ARRAY[]::text[], 'Coquard tradizionale', 'piccole botti di rovere', 'svolta', 300000, NULL, NULL, true, true,
 'Una delle pochissime Maison a utilizzare ancora il pressoir Coquard tradizionale e la fermentazione esclusiva in piccoli fûts de chêne. Fondata nel 1864, produce champagne non filtrati di straordinaria complessità e longevità, quasi borgognoni nel carattere.', 'Artigianalità totale: il pressoir Coquard, le piccole botti di rovere e il rifiuto della filtrazione come scelte identitarie per champagne destinati a durare decenni.', '€€€', false),

('André Beaufort', 'andre-beaufort', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Ambonnay', 'Marne', '1 Rue de Vendanges, 51150 Ambonnay', '+33 3 26 57 01 50', NULL, 1955, 'Famiglia Beaufort', 'Indipendente', 'Jacques Beaufort', 'Jacques Beaufort', 7, 7, NULL, 70, 25, 5, ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere usate', 'svolta parziale', 60000, NULL, 'Vino e Design', false, true,
 'Pioniere assoluto della biodinamica in Champagne, Jacques Beaufort lavora le sue vigne ad Ambonnay e Polisy senza solforosa aggiunta. Champagne di carattere naturale profondo, con fermentazioni spontanee e zero interventi in cantina. Tra i vigneron più coraggiosi e visionari.', 'Zero compromessi: biodinamica integrale, zero solforosa, fermentazioni spontanee. Lo champagne come espressione pura della natura, non della tecnologia.', '€€€', false),

('André Robert', 'andre-robert', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Robert', 'Indipendente', NULL, NULL, 7, 7, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 60000, NULL, NULL, false, true,
 'Vigneron del Grand Cru Le Mesnil-sur-Oger con Blanc de Blancs di straordinaria tensione calcarea. Le vigne storiche su suolo gessoso donano ai vini quella verticalità e longevità che rendono il Mesnil unico al mondo.', 'Il Mesnil-sur-Oger come destino: lo Chardonnay nella sua espressione più pura, minerale e longeva.', '€€€', false),

('Antoine Bouvet', 'antoine-bouvet', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Épernay', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Bouvet', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 35, 35, 30, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Piccolo vigneron con vigne nell''area di Épernay. Produttore artigianale di champagne di carattere con identità territoriale.', 'Artigianalità e autenticità nella tradizione champenoise della Valle della Marna.', '€€', false),

('(AR) Lenoble', 'ar-lenoble', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Damery', 'Marne', '35-37 Rue Paul Douce, 51480 Damery', '+33 3 26 58 42 60', 'www.champagne-lenoble.com', 1920, 'Armand-Raphaël Graser', 'Indipendente', 'Anne et Antoine Malassagne', 'Antoine Malassagne', NULL, NULL, NULL, 40, 40, 20, ARRAY['HVE']::text[], 'pneumatica', 'acciaio inox', 'svolta', 400000, NULL, NULL, true, true,
 'Maison fondata nel 1920 a Damery, rimasta indipendente da quattro generazioni con la famiglia Malassagne al timone. Stile fresco, preciso e di grande bevibilità, con una gamma di rosé particolarmente apprezzata. Grande attenzione alla sostenibilità e alla biodiversità.', 'Indipendenza e freschezza: quattro generazioni della stessa famiglia con la passione per champagne vivaci e precisi, con dosaggi contenuti e rispetto del territorio.', '€€€', false),

('Assailly', 'assailly', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Assailly', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Avize, Grand Cru della Côte des Blancs. Blanc de Blancs di grande purezza e finezza calcarea prodotti con metodi tradizionali.', 'La purezza dello Chardonnay Grand Cru di Avize come filosofia produttiva.', '€€€', false),

-- ── B ──────────────────────────────────────────────────────────

('Benoît Lahaye', 'benoit-lahaye', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Bouzy', 'Marne', '33 Rue Jeanne d''Arc, 51150 Bouzy', '+33 3 26 57 03 05', 'www.champagne-benoit-lahaye.fr', NULL, 'Benoît Lahaye', 'Indipendente', 'Benoît Lahaye', 'Benoît Lahaye', 6, 6, NULL, 75, 20, 5, ARRAY['Biodinamica', 'Demeter']::text[], 'pneumatica', 'botti di rovere', 'svolta parziale', 55000, NULL, 'Vino e Design', false, true,
 'Vigneron biodinamico di Bouzy, Grand Cru della Montagne de Reims. I suoi champagne da Pinot Noir con bassa solforosa e fermentazioni spontanee sono tra i più autentici e commoventi del territorio. Il Rosé de Macération è un capolavoro del genere.', 'Biodinamica come rispetto profondo per la vita: Pinot Noir di Bouzy espresso nella sua forma più naturale e autentica, senza mascherature tecnologiche.', '€€€', false),

('Benoît Munier', 'benoit-munier', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Rilly-la-Montagne', 'Marne', NULL, NULL, NULL, NULL, 'Benoît Munier', 'Indipendente', 'Benoît Munier', 'Benoît Munier', NULL, NULL, NULL, 50, 30, 20, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Rilly-la-Montagne nella Montagne de Reims con approccio artigianale e grande rispetto per il terroir locale. Produzione in piccole quantità con cura per ogni fase.', 'Rispetto per il terroir della Montagne de Reims e artigianalità come valori fondamentali.', '€€€', false),

('Bérêche et Fils', 'bereche-et-fils', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Ludes', 'Marne', '1 Route de Louvois, 51500 Ludes', '+33 3 26 61 13 28', 'www.champagne-bereche-et-fils.com', 1847, 'Famiglia Bérêche', 'Indipendente', 'Raphaël e Vincent Bérêche', 'Raphaël e Vincent Bérêche', 9, 9, NULL, 55, 35, 10, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 80000, NULL, 'Vino e Design', false, true,
 'Domaine familiare di riferimento per il movimento vigneron. Raphaël e Vincent Bérêche producono champagne di straordinaria precisione con vigne in vari crus della Montagne de Reims e della Côte des Blancs. Il Reflet d''Antan è un capolavoro di assemblaggio e complessità. Tra i più ricercati dai collezionisti internazionali.', 'Precisione e identità: ogni vino deve esprimere il carattere specifico del suo terroir d''origine. I vini di riserva vinificati in legno come colonna vertebrale dello stile.', '€€€', false),

('Besserat de Bellefon', 'besserat-de-bellefon', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Épernay', 'Marne', 'Allée du Vignoble, 51200 Épernay', '+33 3 26 78 50 50', 'www.besserat-de-bellefon.com', 1843, 'Groupe Lanson-BCC', 'Lanson-BCC', NULL, NULL, NULL, NULL, NULL, 40, 30, 30, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 1000000, NULL, NULL, true, false,
 'Storica Maison fondata nel 1843, famosa per il suo stile delicato e fine. Oggi parte del gruppo Lanson-BCC, produce la tradizionale Cuvée des Moines apprezzata per eleganza e leggerezza, con basse pressioni e stile aereo.', 'Leggerezza e finezza come identità: lo stile aereo e delicato della Cuvée des Moines come espressione di una Champagne che non teme la sottrazione.', '€€€', false),

('Bolieu', 'bolieu', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Damery', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Bolieu', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 30, 30, 40, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Piccolo vigneron con vigne a Damery nella Valle della Marna. Champagne di carattere artigianale con forte radici territoriali.', 'Autenticità e rispetto della tradizione vitivinicola locale.', '€€', false),

('Brice', 'brice', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Bouzy', 'Marne', '3 Rue Yvonnet, 51150 Bouzy', '+33 3 26 52 06 60', 'www.champagne-brice.fr', 1994, 'Famille Brice', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 55, 30, 15, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 200000, NULL, NULL, true, true,
 'Maison fondata nel 1994 a Bouzy con forte focus su champagne da singoli Grand Crus della Montagne de Reims. Ogni bottiglia riporta il nome del cru d''origine, esaltando le differenze tra Bouzy, Ambonnay, Verzenay e Ay.', 'Il Grand Cru come linguaggio: ogni terroir racconta una storia diversa attraverso il Pinot Noir, con la trasparenza dell''origine come valore fondante.', '€€€', false),

-- ── C ──────────────────────────────────────────────────────────

('C.H. Piconnet', 'ch-piconnet', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', NULL, NULL, NULL, NULL, 'Famiglia Piconnet', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron della Côte des Blancs con vigne nel Grand Cru Avize. Blanc de Blancs di carattere minerale prodotti in piccole quantità.', 'Il Grand Cru Avize come territorio di elezione per Blanc de Blancs di grande purezza.', '€€€', false),

('Cazals', 'cazals', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', '28 Rue du Grand Mont, 51190 Le Mesnil-sur-Oger', '+33 3 26 57 52 26', 'www.champagne-cazals.fr', 1897, 'Famille Cazals', 'Indipendente', 'Delphine Cazals', 'Delphine Cazals', 10, 10, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 80000, NULL, NULL, false, true,
 'Maison familiare con vigne nei Grand Crus della Côte des Blancs da oltre un secolo. Il Clos Cazals, parcella murata nel cuore di Le Mesnil-sur-Oger, è uno dei champagne da singola vigna più ricercati. Delphine Cazals guida il domaine con grande rigore e rispetto per la tradizione.', 'Il Grand Cru Le Mesnil-sur-Oger come destino: il Clos Cazals come interpretazione più pura del terroir gessoso che ha reso questo comune leggendario.', '€€€€', false),

('Cazé-Thibaut', 'caze-thibaut', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Jonquery', 'Marne', NULL, NULL, NULL, NULL, 'Famille Cazé-Thibaut', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 20, 20, 60, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale', NULL, NULL, NULL, false, false,
 'Vigneron di Jonquery nella Valle della Marna con approccio naturale e rispetto per la biodiversità. Champagne da Meunier di grande bevibilità e carattere autentico.', 'Il Pinot Meunier come protagonista: valorizzazione di un vitigno troppo spesso sottovalutato attraverso un approccio rispettoso della natura.', '€€€', false),

('Chartogne-Taillet', 'chartogne-taillet', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Merfy', 'Marne', '37-39 Grande Rue, 51220 Merfy', '+33 3 26 03 10 17', 'www.chartogne-taillet.com', 1919, 'Famille Chartogne', 'Indipendente', 'Alexandre Chartogne', 'Alexandre Chartogne', 12, 12, NULL, 40, 40, 20, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 80000, NULL, 'Vino e Design', false, true,
 'Alexandre Chartogne è tra i vigneron più intellettualmente stimolanti della Champagne. A Merfy, ai piedi della Montagne de Reims, produce champagne da singole parcelle — Héloïse, Orizeaux, Fiacre — che esprimono le sfumature di un terroir ricco e complesso. La sua collaborazione con Anselme Selosse ha segnato una svolta stilistica.', 'Ogni parcella come universo: la vigna di Merfy racconta storie diverse e Alexandre le traduce in champagne di rara precisione e individualità.', '€€€', false),

('Christian Gosset', 'christian-gosset', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Aÿ', 'Marne', NULL, NULL, NULL, NULL, 'Christian Gosset', 'Indipendente', 'Christian Gosset', 'Christian Gosset', NULL, NULL, NULL, 70, 20, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Aÿ, Grand Cru della Montagne de Reims. Champagne di struttura e profondità da uno dei terroir più rinomati per il Pinot Noir.', 'Il Grand Cru Aÿ come vocazione: Pinot Noir di struttura e carattere in piccole quantità artigianali.', '€€€', false),

('Clandestin', 'clandestin', 'RM', NULL, 'Buxeuil', 'Aube', NULL, NULL, NULL, NULL, 'Famille Clandestin', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 80, 10, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale', NULL, NULL, NULL, false, false,
 'Piccola casa dell''Aube con approccio anticonformista e champagne di carattere naturale. Il nome stesso — Clandestin — evoca uno spirito ribelle e fuori dagli schemi della Champagne convenzionale.', 'Rifiuto del conformismo: champagne naturali e autentici dall''Aube, territorio ancora poco esplorato ma ricco di potenziale.', '€€€', false),

('Colin', 'colin', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Avenay-Val-d''Or', 'Marne', NULL, NULL, NULL, NULL, 'Famille Colin', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 50, 30, 20, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Avenay-Val-d''Or nella Montagne de Reims. Premier Cru ricco e complesso che dona ai vini equilibrio tra struttura e freschezza.', 'Il Premier Cru Avenay come territorio di espressione: champagne di bella complessità e identità territoriale.', '€€€', false),

('Collard-Picard', 'collard-picard', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Vandières', 'Marne', NULL, NULL, NULL, NULL, 'Famille Collard-Picard', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 25, 25, 50, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Vandières nella Valle della Marna. Champagne con forte identità territoriale valorizzando il Pinot Meunier del territorio.', 'La Valle della Marna e il Meunier come radici: champagne autentici da un terroir ricco di sfumature.', '€€€', false),

('Corbon', 'corbon', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', NULL, NULL, NULL, NULL, 'Famille Corbon', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Avize, Grand Cru della Côte des Blancs. Blanc de Blancs di grande mineralità e finezza gessosa, prodotti in piccole quantità con rispetto per la tradizione.', 'Lo Chardonnay di Avize Grand Cru nella sua espressione più pura: mineralità, verticalità e longevità.', '€€€', false),

('Crucifix', 'crucifix', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Aÿ', 'Marne', NULL, NULL, NULL, NULL, 'Famille Crucifix', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 65, 25, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Aÿ, Grand Cru della Montagne de Reims. Champagne di struttura e carattere da uno dei terroir più prestigiosi per il Pinot Noir champenois.', 'Il Grand Cru Aÿ come punto di partenza: Pinot Noir strutturato e champagne di grande personalità.', '€€€', false),

-- ── D ──────────────────────────────────────────────────────────

('Damien Hugot', 'damien-hugot', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Épernay', 'Marne', NULL, NULL, NULL, NULL, 'Damien Hugot', 'Indipendente', 'Damien Hugot', 'Damien Hugot', NULL, NULL, NULL, 35, 35, 30, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Giovane vigneron nell''area di Épernay con approccio artigianale e grande attenzione alla vigna. Champagne di carattere e bevibilità con dosaggi contenuti.', 'Artigianalità e rispetto per la vigna: ogni bottiglia riflette il lavoro silenzioso di chi privilegia la qualità alla quantità.', '€€€', false),

('David Léclapart', 'david-leclapart', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Trépail', 'Marne', '10 Rue de la Mairie, 51380 Trépail', '+33 3 26 57 07 01', NULL, NULL, 'David Léclapart', 'Indipendente', 'David Léclapart', 'David Léclapart', 3, 3, NULL, 5, 90, 5, ARRAY['Biodinamica', 'Demeter']::text[], 'pneumatica', 'botti di rovere usate', 'non svolta', 15000, NULL, 'Vino e Design', false, false,
 'Vigneron biodinamico di riferimento assoluto a Trépail, Premier Cru della Montagne de Reims. Tre soli vini — L''Apôtre, L''Artiste, L''Amateur — prodotti in quantità minime da Chardonnay su suolo calcaro-siliceo. Tra i più ricercati e introvabili del mondo.', 'La biodinamica come religione e il Chardonnay di Trépail come preghiera: tre vini, tremila bottiglie, una visione cristallina del terroir come identità assoluta.', '€€€€', false),

('De Sousa', 'de-sousa', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', '12 Place Léon Bourgeois, 51190 Avize', '+33 3 26 57 53 29', 'www.champagnedesousa.com', 1986, 'Famille de Sousa', 'Indipendente', 'Mickaël de Sousa', 'Erick de Sousa', 10, 10, NULL, 5, 90, 5, ARRAY['Biodinamica', 'Demeter']::text[], 'pneumatica', 'botti di rovere usate', 'svolta', 100000, NULL, 'Vino e Design', false, true,
 'Domaine biodinamico fondato nel 1986 da Erick de Sousa, oggi condotto dal figlio Mickaël. Vigne nei Grand Crus della Côte des Blancs con approccio rigorosamente biodinamico. Il Cuvée des Caudalies e il Mycorhize sono tra i Blanc de Blancs extra-brut più complessi e longevi esistenti.', 'La biodinamica come rispetto per la vita del suolo: il Chardonnay della Côte des Blancs espresso nella sua forma più complessa attraverso fermentazioni in legno e lunghissimi affinamenti.', '€€€€', false),

('De Venoge', 'de-venoge', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Épernay', 'Marne', '33 Avenue de Champagne, 51200 Épernay', '+33 3 26 53 34 34', 'www.champagnedevenoge.com', 1837, 'Groupe BCC', 'BCC', NULL, NULL, NULL, NULL, NULL, 35, 30, 35, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 1500000, NULL, NULL, true, false,
 'Storica Maison fondata nel 1837 a Épernay, oggi parte del gruppo BCC. Famosa per le eleganti bottiglie con etichetta dei Princes de France e i Cordon Bleu. La Cuvée des Princes Blanc de Blancs è la bottiglia di punta.', 'Eleganza e storia: lo stile classico di Épernay nella tradizione delle grandi Maison, con il Blanc de Blancs millesimato come massima espressione.', '€€€', false),

('Delavenne', 'delavenne', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Bouzy', 'Marne', NULL, NULL, NULL, NULL, 'Famille Delavenne', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 80, 15, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Bouzy, Grand Cru della Montagne de Reims. Pinot Noir di grande struttura e profondità da uno dei Grand Crus più celebri per il vitigno.', 'Il Grand Cru Bouzy e il Pinot Noir come vocazione: struttura, colore e complessità in ogni bottiglia.', '€€€', false),

('Devaux', 'devaux', 'NM', NULL, 'Bar-sur-Seine', 'Aube', 'Hameau de Villeneuve-la-Grande, 10110 Bar-sur-Seine', '+33 3 25 38 30 65', 'www.champagne-devaux.fr', 1846, 'Coopérative de l''Aube', 'Indipendente', 'Michel Drappier (consulente)', 'Charlène Rinville', NULL, NULL, NULL, 90, 5, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale', 1000000, NULL, NULL, true, true,
 'Maison dell''Aube fondata nel 1846, espressione del Pinot Noir autoctono di questa zona spesso trascurata. La D de Devaux, prodotta in collaborazione con Michel Chapoutier, è un Blanc de Noirs millesimato di straordinaria profondità. L''Aube produce Pinot Noir di grande carattere su suoli kimmeridgiani simili a quelli di Chablis.', 'Il Pinot Noir dell''Aube come riscatto: suoli kimmeridgiani, clima continentale e una tradizione vitivinicola secolare che merita il riconoscimento che le spetta.', '€€€', false),

('Dhondt-Grellet', 'dhondt-grellet', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Festigny', 'Marne', NULL, NULL, NULL, NULL, 'Famille Dhondt-Grellet', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 15, 15, 70, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale', NULL, NULL, 'Vino e Design', false, false,
 'Vigneron di Festigny nella Valle della Marna. Guillaume Dhondt produce champagne da Meunier di grande bevibilità e autenticità, con approccio naturale e bassa solforosa. Uno dei migliori interpreti del Pinot Meunier.', 'Il Meunier come protagonista assoluto: Festigny come terroir d''elezione per un vitigno che in mani esperte rivela complessità e profondità inaspettate.', '€€€', false),

('Diebolt-Vallois', 'diebolt-vallois', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Cramant', 'Marne', '84 Rue Neuve, 51530 Cramant', '+33 3 26 57 54 92', NULL, NULL, 'Famille Diebolt', 'Indipendente', 'Jacques Diebolt', 'Jacques Diebolt', 10, 10, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 80000, NULL, NULL, false, true,
 'Vigneron di Cramant, Grand Cru della Côte des Blancs. Specializzato in Blanc de Blancs di grande mineralità, finezza e longevità eccezionale. Il Fleur de Passion millesimato è un''interpretazione sublime del calcario di Cramant.', 'Cramant Grand Cru come espressione unica: lo Chardonnay su suolo gessoso nella sua versione più cremosa e longeva, con il millesimato come vertice assoluto.', '€€€', false),

('Dom Pérignon', 'dom-perignon', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Épernay', 'Marne', '20 Avenue de Champagne, 51200 Épernay', '+33 3 26 51 20 00', 'www.domperignon.com', 1668, 'LVMH', 'LVMH', 'Vincent Chaperon', 'Vincent Chaperon', NULL, NULL, NULL, 35, 35, 30, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 5000000, NULL, 'Moët Hennessy Italia', false, false,
 'La prestige cuvée di Moët & Chandon, prodotta solo nelle annate eccezionali. Prende il nome dal monaco benedettino Dom Pierre Pérignon, cellaio dell''abbazia di Hautvillers. Ogni Dom Pérignon viene rilasciato solo quando raggiunge la sua première plénitude — il momento di piena espressione. Icona assoluta del lusso mondiale.', 'La plénitude come filosofia: ogni Dom Pérignon viene rilasciato solo al momento perfetto, con le successive éditions Plénitude 2 e 3 che rivelano come il tempo trasformi il vino in qualcosa di straordinario.', '€€€€', false),

('Doyard', 'doyard', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Vertus', 'Marne', '63 Avenue du Général Leclerc, 51130 Vertus', '+33 3 26 52 14 74', 'www.champagne-doyard.fr', 1927, 'Famille Doyard', 'Indipendente', 'Yannick Doyard', 'Yannick Doyard', 13, 13, NULL, 5, 90, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale', 80000, NULL, NULL, false, true,
 'Domaine di Vertus, Premier Cru della Côte des Blancs. Yannick Doyard produce Blanc de Blancs di grande verticalità e finezza calcarea, con frequenti vendemmie tardive per massimizzare la maturità fenolica. La Cuvée Vendémiaire è un classico della tipologia.', 'La maturità come scelta: vendemmie tardive e Chardonnay di Vertus per champagne di grande profondità e tensione tra freschezza e maturità.', '€€€', false),

('Drappier', 'drappier', 'NM', NULL, 'Urville', 'Aube', '6 Rue des Vignes, 10200 Urville', '+33 3 25 27 40 15', 'www.champagne-drappier.com', 1808, 'Famille Drappier', 'Indipendente', 'Michel e Antoine Drappier', 'Antoine Drappier', 65, 65, NULL, 90, 5, 5, ARRAY['HVE']::text[], 'pneumatica', 'acciaio inox', 'svolta', 2000000, NULL, 'Pellegrini SpA', true, true,
 'Maison familiare dell''Aube fondata nel 1808, custode di una tradizione vitivinicola tra le più antiche della regione. Michel e Antoine Drappier guidano con passione un''azienda che valorizza il Pinot Noir dell''Aube. L''Ultra Brut — senza dosaggio — e il Grande Sendrée millesimato sono tra le bottiglie più apprezzate dai conoscitori.', 'Il Pinot Noir dell''Aube e la sostenibilità come valori: bioedilizia della cantina, riduzione della solforosa e rispetto per un territorio troppo a lungo ignorato dalle guide internazionali.', '€€€', false),

('Duval-Leroy', 'duval-leroy', 'NM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Vertus', 'Marne', '69 Avenue de Bammental, 51130 Vertus', '+33 3 26 52 60 00', 'www.duval-leroy.com', 1859, 'Famille Duval-Leroy', 'Indipendente', 'Carol Duval-Leroy', 'Sandrine Logette-Jardin', 200, 200, NULL, 20, 60, 20, ARRAY['HVE']::text[], 'pneumatica', 'acciaio inox', 'svolta', 5000000, NULL, 'Pellegrini SpA', true, true,
 'Maison fondata nel 1859 a Vertus. Carol Duval-Leroy ha trasformato con determinazione la casa in una delle più rispettate della regione, con grande focus sulla Côte des Blancs. La Femme de Champagne, il Blanc de Blancs Authentis e la serie Authentic Terroir sono tra le espressioni più eleganti.', 'Femminilità, sostenibilità e Côte des Blancs: Carol Duval-Leroy incarna una visione moderna della grande Champagne, con lo Chardonnay come filo conduttore di uno stile fresco e gastronomico.', '€€€', false)

ON CONFLICT (slug) DO NOTHING;

-- ================================================================
-- BATCH 2 — E → L
-- ================================================================

INSERT INTO maison (nome, slug, tipo, zona_id, sede_comune, sede_regione, sede_indirizzo, telefono, sito_web, anno_fondazione, proprieta, gruppo, direzione, chef_de_cave, ettari_totali, ettari_proprieta, ettari_gestione, pct_pinot_noir, pct_chardonnay, pct_meunier, certificazioni, tipo_pressa, vinificazione, malolattica, produzione_bottiglie, stock_cantina, importatore_italia, visita_possibile, degustazione_possibile, descrizione, filosofia, fascia_prezzo, is_free) VALUES

('Etienne Calsac', 'etienne-calsac', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', NULL, NULL, 'www.etiennecalsac.com', NULL, 'Etienne Calsac', 'Indipendente', 'Etienne Calsac', 'Etienne Calsac', 3, 3, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale', 20000, NULL, 'Vino e Design', false, true,
 'Giovane vigneron della Côte des Blancs con forte identità e approccio moderno. L''Echappée Belle — il suo blanc de blancs di riferimento — è uno champagne di grande tensione calcarea e precisione stilistica che ha conquistato rapidamente critica e collezionisti.', 'La nuova generazione della Côte des Blancs: precisione moderna, basse rese e Chardonnay di Avize per champagne che guardano al futuro senza dimenticare il terroir.', '€€€', false),

('Francis Boulard et Fille', 'francis-boulard-et-fille', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Cauroy-lès-Hermonville', 'Marne', NULL, NULL, 'www.champagne-boulard.fr', NULL, 'Famille Boulard', 'Indipendente', 'Marine Boulard', 'Marine Boulard', 10, 10, NULL, 55, 35, 10, ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 60000, NULL, NULL, false, true,
 'Domaine familiare con vigne nella Montagne de Reims settentrionale, area meno nota ma di grande potenziale. Marine Boulard guida oggi il domaine con approccio biodinamico e produzione di champagne da singole parcelle di grande autenticità e carattere territoriale.', 'La Montagne de Reims settentrionale come territorio da riscoprire: biodinamica e singole parcelle per champagne che raccontano zone ancora poco esplorate dalla grande critica.', '€€€', false),

('Franck Bonville', 'franck-bonville', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', '9 Rue Pasteur, 51190 Avize', '+33 3 26 57 52 30', 'www.champagne-franck-bonville.com', 1947, 'Famille Bonville', 'Indipendente', 'Olivier Bonville', 'Olivier Bonville', 10, 10, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 80000, NULL, NULL, false, true,
 'Vigneron di Avize da tre generazioni con vigne nei Grand Crus della Côte des Blancs. Olivier Bonville produce Blanc de Blancs di grande eleganza floreale e mineralità, con il Les Belles Voyes come cuvée parcellaire di riferimento. Un classico dello stile Avize.', 'Il Grand Cru Avize come patrimonio di famiglia: tre generazioni di Bonville per un Blanc de Blancs che esprime l''eleganza e il carattere inconfondibile di questo terroir gessoso.', '€€€', false),

('Franck Pascal', 'franck-pascal', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Baslieux-sous-Châtillon', 'Marne', NULL, NULL, NULL, NULL, 'Franck Pascal', 'Indipendente', 'Franck Pascal', 'Franck Pascal', 7, 7, NULL, 20, 20, 60, ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere', 'non svolta', 40000, NULL, NULL, false, false,
 'Pioniere della biodinamica radicale nella Valle della Marna. Franck Pascal produce champagne naturali con fermentazioni spontanee, zero solforosa e affinamenti in legno. Uno stile unico e coraggioso che valorizza il Meunier come vitigno d''eccellenza.', 'Zero compromessi in vigna e in cantina: la biodinamica come stile di vita e il Meunier come vitigno nobile per champagne che sfidano le convenzioni.', '€€€', false),

('Frerejean Frères', 'frerejean-freres', 'NM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', '10 Allée de la Forêt, 51190 Avize', NULL, 'www.frerejean-freres.com', 2005, 'Famille Frerejean', 'Indipendente', 'Rodolphe, Emeric e Edouard Frerejean', NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 200000, NULL, NULL, true, true,
 'Maison fondata nel 2005 da tre fratelli con focus esclusivo su Blanc de Blancs di alta qualità dalla Côte des Blancs. In pochi anni si sono imposti come una delle realtà più dinamiche della regione con champagne di grande precisione e eleganza contemporanea.', 'Il Blanc de Blancs come unica ragion d''essere: tre fratelli uniti dalla passione per lo Chardonnay della Côte des Blancs in uno stile moderno e senza compromessi.', '€€€', false),

('Fresnet-Julliet', 'fresnet-julliet', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Verzenay', 'Marne', NULL, NULL, NULL, NULL, 'Famille Fresnet', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 85, 10, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Verzenay, Grand Cru della Montagne de Reims per eccellenza del Pinot Noir. Champagne di grande struttura e profondità da uno dei terroir più rinomati della regione.', 'Il Grand Cru Verzenay come vocazione: Pinot Noir di struttura e potenza espressiva in ogni bottiglia.', '€€€', false),

('Gallois-Bouché', 'gallois-bouche', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Rilly-la-Montagne', 'Marne', NULL, NULL, NULL, NULL, 'Famille Gallois-Bouché', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 45, 30, 25, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Rilly-la-Montagne nella Montagne de Reims con approccio artigianale e rispetto per il terroir locale. Produzione in piccole quantità.', 'La tradizione artigianale di Rilly-la-Montagne come base di un''identità territoriale autentica.', '€€€', false),

('Geoffroy', 'geoffroy', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Aÿ', 'Marne', '150 Rue du Bois des Jots, 51160 Aÿ', '+33 3 26 55 32 31', 'www.champagne-geoffroy.com', 1600, 'Famille Geoffroy', 'Indipendente', 'René Geoffroy', 'René Geoffroy', 15, 15, NULL, 60, 25, 15, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta', 120000, NULL, NULL, false, true,
 'Una delle famiglie vitivinicole più antiche della Champagne, con vigne ad Aÿ da oltre 400 anni. René Geoffroy produce champagne di grande autenticità e senso del terroir con fermentazioni in legno e rispetto per le tradizioni più antiche. Il Volupté è la cuvée di riferimento del domaine.', 'Quattro secoli di storia ad Aÿ: René Geoffroy reinterpreta la tradizione centenaria della sua famiglia attraverso vinificazioni in legno e un rispetto profondo per l''eredità ricevuta.', '€€€', false),

('Georges Remy', 'georges-remy', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Bouzy', 'Marne', NULL, NULL, NULL, NULL, 'Famille Remy', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 80, 15, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Bouzy, Grand Cru della Montagne de Reims. Pinot Noir di grande struttura e autenticità da uno dei terroir più celebri per il vitigno in Champagne.', 'Il Grand Cru Bouzy come terroir di elezione per il Pinot Noir champenois nella sua espressione più autentica.', '€€€', false),

('Girard-Bonnet', 'girard-bonnet', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', NULL, NULL, NULL, NULL, 'Famille Girard-Bonnet', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron della Côte des Blancs con vigne ad Avize Grand Cru. Blanc de Blancs di grande purezza e impronta minerale.', 'La purezza del Grand Cru Avize come unico obiettivo produttivo.', '€€€', false),

('Gonet-Medeville', 'gonet-medeville', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', '1 Chemin de la Cavotte, 51190 Bisseuil', '+33 3 26 57 52 70', 'www.gonet-medeville.com', 1830, 'Julie Gonet-Médeville', 'Indipendente', 'Julie Gonet-Médeville', 'Julie Gonet-Médeville', 10, 10, NULL, 30, 65, 5, ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 60000, NULL, 'Vino e Design', false, true,
 'Maison familiare con vigne a Le Mesnil-sur-Oger e Bisseuil. Julie Gonet-Médeville è una delle figure più rispettate del panorama vigneron, con approccio biodinamico e champagne di grande finezza e complessità. Il Theophile millesimato è uno dei Blanc de Blancs più eleganti.', 'La biodinamica al servizio del terroir: Julie Gonet-Médeville coniuga il rigore scientifico con la sensibilità artigianale per champagne di rara eleganza e finezza.', '€€€', false),

('Gustave Goussard', 'gustave-goussard', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', NULL, NULL, NULL, NULL, 'Famille Goussard', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron del Grand Cru Le Mesnil-sur-Oger con Blanc de Blancs di grande mineralità gessosa e tensione verticale. Una delle espressioni più classiche del terroir di Mesnil.', 'Il Grand Cru Le Mesnil-sur-Oger nella sua interpretazione più tradizionale: verticalità, mineralità e longevità come tratti distintivi.', '€€€', false),

('Guy Charlemagne', 'guy-charlemagne', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', '4 Rue de la Brèche d''Oger, 51190 Le Mesnil-sur-Oger', '+33 3 26 57 52 98', 'www.guy-charlemagne.com', 1892, 'Famille Charlemagne', 'Indipendente', 'Philippe Charlemagne', 'Philippe Charlemagne', 15, 15, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 100000, NULL, NULL, false, true,
 'Domaine storico del Grand Cru Le Mesnil-sur-Oger da oltre un secolo. Philippe Charlemagne produce Blanc de Blancs di straordinaria mineralità gessosa, con il Mesnillésime — parcella di vigne vecchie sul versante est del Mesnil — considerato uno dei migliori Blanc de Blancs millesimati al mondo.', 'Il Le Mesnil-sur-Oger come destino e il Mesnillésime come vertice: un''interpretazione centenaria del Grand Cru più gessoso e longevo della Côte des Blancs.', '€€€', false),

('Henri Giraud', 'henri-giraud', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Aÿ', 'Marne', '41 Boulevard Charles de Gaulle, 51160 Aÿ', '+33 3 26 55 18 55', 'www.champagne-henri-giraud.com', 1625, 'Famille Giraud', 'Indipendente', 'Claude Giraud', 'Sébastien Le Golvet', 30, 26, 4, 60, 30, 10, ARRAY[]::text[], 'pneumatica', 'piccole botti di rovere d''Argonne', 'svolta parziale', 200000, NULL, 'Pellegrini SpA', true, true,
 'Maison con radici nel 1625 ad Aÿ. Claude Giraud ha trasformato questa storica casa attraverso la fermentazione in piccoli fûts de chêne d''Argonne di diverse stagionature. Il Code Noir e il Fût de Chêne MV09 sono tra i champagne più complessi e longevi, con un profilo vinoso e ossidativo unico in tutta la regione.', 'Il rovere d''Argonne come strumento di complessità: piccole botti, ossigenazione progressiva e il Grand Cru Aÿ per champagne che sfidano ogni categorizzazione stilistica.', '€€€€', false),

('Huré Frères', 'hure-freres', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Ludes', 'Marne', '2 Rue des Genêts, 51500 Ludes', '+33 3 26 61 11 09', 'www.hure-freres.com', 1960, 'Pierre e François Huré', 'Indipendente', 'Pierre Huré', 'Pierre e François Huré', 10, 10, NULL, 50, 35, 15, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 80000, NULL, 'Vino e Design', false, true,
 'Pierre e François Huré a Ludes, Premier Cru della Montagne de Reims. I loro champagne — in particolare l''Inattendu e il Mémoire — sono di grande equilibrio e precisione, con vini di riserva vinificati in legno e affinamenti prolungati. Tra i vigneron più apprezzati dai sommelier.', 'Equilibrio e precisione come filosofia: i vini di riserva in legno come memoria del territorio e la collaborazione fraterna come forza per champagne di grande coerenza stilistica.', '€€€', false),

('Jacques Rousseaux', 'jacques-rousseaux', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Verzenay', 'Marne', NULL, NULL, NULL, NULL, 'Famille Rousseaux', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 90, 5, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron del Grand Cru Verzenay con Pinot Noir di grande struttura, profondità e potenza espressiva da uno dei terroir più rinomati della Montagne de Reims.', 'Il Grand Cru Verzenay come territorio di elezione per il Pinot Noir champenois nella sua espressione più potente e longeva.', '€€€', false),

('JM Goulard', 'jm-goulard', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Chouilly', 'Marne', NULL, NULL, NULL, NULL, 'Famille Goulard', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Chouilly, Grand Cru della Côte des Blancs. Blanc de Blancs di grande eleganza e finezza da uno dei comuni meno celebrati ma di alto valore della zona.', 'Il Grand Cru Chouilly come terroir da valorizzare: Chardonnay di grande eleganza in uno stile classico e rispettoso della tradizione.', '€€€', false),

('JM Séléque', 'jm-seleque', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Pierry', 'Marne', NULL, NULL, 'www.seleque-champagne.fr', NULL, 'Jean-Marc Séléque', 'Indipendente', 'Jean-Marc Séléque', 'Jean-Marc Séléque', 8, 8, NULL, 35, 35, 30, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 50000, NULL, 'Vino e Design', false, true,
 'Jean-Marc Séléque produce a Pierry, vicino a Épernay, champagne da singole parcelle di grande precisione e modernità. La sua gamma — Solessence, Partition, Quintette — esplora le diverse sfumature di un terroir composito con rigore scientifico e sensibilità artigianale.', 'La parcella come unità di misura: ogni vino racconta il carattere specifico di un luogo, con la modernità come strumento per esprimere la tradizione.', '€€€', false),

('Julien Herbert', 'julien-herbert', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Villers-Marmery', 'Marne', NULL, NULL, NULL, NULL, 'Julien Herbert', 'Indipendente', 'Julien Herbert', 'Julien Herbert', NULL, NULL, NULL, 10, 80, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Villers-Marmery, Premier Cru atipico della Montagne de Reims dove domina lo Chardonnay in un''area tipicamente a Pinot Noir. Champagne di bella tensione e carattere minerale unico.', 'Villers-Marmery come eccezione: lo Chardonnay in un mare di Pinot Noir, per champagne di grande originalità e tensione minerale.', '€€€', false),

('La Closerie', 'la-closerie', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Gueux', 'Marne', NULL, NULL, NULL, NULL, 'Jérôme Prévost', 'Indipendente', 'Jérôme Prévost', 'Jérôme Prévost', 2, 2, NULL, 5, 5, 90, ARRAY[]::text[], 'pneumatica', 'botti di rovere usate', 'svolta', 5000, NULL, 'Vino e Design', false, false,
 'Jérôme Prévost produce a Gueux una sola cuvée: Les Béguines, da Pinot Meunier su suoli sabbiosi silicei. Poche migliaia di bottiglie che sono tra le più ricercate e costose del panorama vigneron mondiale. Un vino unico per terroir, vitigno e approccio — quasi un unicum in Champagne.', 'Un solo vino, un solo vitigno, un solo luogo: il Meunier di Gueux su sabbie silicee come espressione irripetibile di un terroir senza paragoni in Champagne.', '€€€€', false),

('La Renaissance', 'la-renaissance', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Festigny', 'Marne', NULL, NULL, NULL, NULL, 'Famille La Renaissance', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 20, 20, 60, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Festigny nella Valle della Marna con approccio artigianale e tradizionale. Champagne che valorizzano il Meunier del territorio con carattere autentico.', 'La Valle della Marna e il Meunier come tradizione da preservare e valorizzare.', '€€', false),

('La Villesenière', 'la-villeseniere', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Villeneuve-Renneville', 'Marne', NULL, NULL, NULL, NULL, 'Famille Villesenière', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 5, 90, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron della Côte des Blancs meridionale con Blanc de Blancs di bella mineralità e freschezza da un terroir meno esplorato ma di grande potenziale.', 'La Côte des Blancs meridionale come territorio da valorizzare: Chardonnay di grande freschezza e mineralità.', '€€€', false),

('Lacourte-Godbillon', 'lacourte-godbillon', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Écueil', 'Marne', '5 Rue de Louvois, 51500 Écueil', '+33 3 26 49 72 63', 'www.lacourte-godbillon.fr', NULL, 'Famille Lacourte', 'Indipendente', 'Richard Lacourte', 'Richard Lacourte', 7, 7, NULL, 50, 35, 15, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 50000, NULL, NULL, false, true,
 'Vigneron di Écueil, Premier Cru della Montagne de Reims. Richard Lacourte produce champagne da singole parcelle con grande cura e rispetto per un terroir fresco e minerale. Il Territoires d''Écueil è il manifesto del progetto.', 'Écueil come terroir d''elezione: la freschezza della Montagne de Reims in un approccio parcellare che rivela le sfumature di un Premier Cru troppo spesso trascurato.', '€€€', false),

('Lafalise-Froissart', 'lafalise-froissart', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Trélou-sur-Marne', 'Marne', NULL, NULL, NULL, NULL, 'Famille Lafalise-Froissart', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 20, 20, 60, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Trélou-sur-Marne nella Valle della Marna con approccio artigianale e grande rispetto per il territorio e il Meunier locale.', 'La Valle della Marna nella sua espressione più autentica e artigianale.', '€€', false),

('Lagille', 'lagille', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Montigny-sous-Châtillon', 'Marne', NULL, NULL, NULL, NULL, 'Famille Lagille', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 20, 20, 60, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Montigny-sous-Châtillon nella Valle della Marna con champagne di carattere artigianale da un terroir ricco di sfumature.', 'Artigianalità e rispetto per il terroir della Valle della Marna.', '€€', false),

('Laherte Frères', 'laherte-freres', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Chavot-Courcourt', 'Marne', '3 Rue des Jardins, 51530 Chavot-Courcourt', '+33 3 26 54 32 09', 'www.champagne-laherte.com', NULL, 'Aurélien Laherte', 'Indipendente', 'Aurélien Laherte', 'Aurélien Laherte', 10, 10, NULL, 30, 30, 40, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 80000, NULL, 'Vino e Design', false, true,
 'Aurélien Laherte è una delle figure più creative e rigorose del panorama vigneron. Vicino a Épernay, produce champagne naturali di grande finezza da vigne in diversi terroirs. Les 7, assemblaggio di tutti e 7 i vitigni champenois inclusi i cépages oubliés (Arbane, Petit Meslier, Pinot Blanc), è la sua cuvée più emblematica.', 'Curiosità intellettuale e rispetto per la biodiversità: les 7 vitigni champenois come patrimonio da preservare, con la spontaneità delle fermentazioni come strumento per esprimere l''autenticità del terroir.', '€€€', false),

('Lallier', 'lallier', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Aÿ', 'Marne', '4 Place de la Libération, 51160 Aÿ', '+33 3 26 55 43 40', 'www.champagne-lallier.com', 1996, 'Campari Group', 'Campari Group', 'Francis Tribaut', 'Francis Tribaut', NULL, NULL, NULL, 55, 35, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 500000, NULL, 'Campari Italia', true, true,
 'Maison fondata nel 1996 ad Aÿ, oggi di proprietà del Campari Group. Produce champagne di grande eleganza con forte focus sulla materia prima del Grand Cru Aÿ, con Francis Tribaut come cellarmaster. La Grand Cru e la R.O12 Blanc de Blancs sono le referenze di punta.', 'Il Grand Cru Aÿ come fondamento: struttura, profondità e eleganza champenoise in uno stile moderno che rispetta la grande tradizione del territorio.', '€€€', false),

('Lanson', 'lanson', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Reims', 'Marne', '66 Rue de Courlancy, 51100 Reims', '+33 3 26 78 50 50', 'www.lanson.com', 1760, 'Groupe BCC', 'BCC', NULL, 'Hervé Dantan', NULL, NULL, NULL, 50, 30, 20, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'non svolta', 7000000, NULL, NULL, true, false,
 'Una delle grandi Maison storiche di Reims, fondata nel 1760. Celebre per la sua scelta di non effettuare la fermentazione malolattica — una rarità tra le grandi case — che dona ai vini una freschezza e una tensione acida inconfondibili. Il Black Label e il Green Label (Extra Age) esprimono perfettamente questo stile verticale e longevo.', 'La malolattica non svolta come identità assoluta: la freschezza e la tensione acida come firma stilistica, con vini che richiedono tempo ma regalano una longevità straordinaria.', '€€€', false),

('Laval Aurore & Florian', 'laval-aurore-florian', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Cumières', 'Marne', NULL, NULL, NULL, NULL, 'Famille Laval', 'Indipendente', 'Aurore e Florian Laval', 'Aurore e Florian Laval', NULL, NULL, NULL, 50, 20, 30, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Cumières, Premier Cru con microclima caldo favorevole al Pinot Noir sulla riva sinistra della Marna. Champagne di bella intensità fruttata e struttura.', 'Cumières e il suo microclima unico: Pinot Noir maturo e fruttato da un terroir soleggiato sulla riva della Marna.', '€€€', false),

('Leclerc Briant', 'leclerc-briant', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Épernay', 'Marne', '67 Rue Claude Ruelle, 51200 Épernay', '+33 3 26 54 45 33', 'www.leclercbriant.com', 1872, 'Maisons & Domaines Henriot', 'Henriot Group', 'Frédéric Zeimett', 'Hervé Jestin', 30, 30, NULL, 35, 40, 25, ARRAY['Biodinamica', 'Demeter']::text[], 'pneumatica', 'botti di rovere e anfore', 'svolta parziale', 200000, NULL, 'Rinaldi Importatori', false, true,
 'Maison storica di Épernay rinata grazie all''investimento americano nel 2012. Produce champagne biodinamici di grande espressività da parcelle singole — Les Chèvres Pierreuses, Les Clos, Les Authentiques. Hervé Jestin usa anfore e barrique per vinificazioni di grande complessità e originalità.', 'La biodinamica e le singole parcelle come manifesto: vinificazioni in anfore e legno per champagne che raccontano storie specifiche di suoli, esposizioni e microclimi di Épernay e dintorni.', '€€€', false),

('Legras & Haas', 'legras-haas', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Chouilly', 'Marne', '35 Rue de Rémont, 51530 Chouilly', '+33 3 26 55 43 61', 'www.champagne-legras-haas.com', 1991, 'Famille Legras-Haas', 'Indipendente', 'François Legras', 'François Legras', 22, 22, NULL, 5, 90, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 150000, NULL, NULL, false, true,
 'Domaine di Chouilly, Grand Cru della Côte des Blancs. François Legras produce Blanc de Blancs di grande precisione e verticalità, con vigne in diversi Grand Crus della Côte. Il Présidence millesimato e l''Infiniment Blanc de Blancs sono le referenze più acclamate.', 'La precisione della Côte des Blancs attraverso Chardonnay da Grand Crus selezionati: ogni bottiglia esprime la verticalità e la mineralità proprie di questo territorio.', '€€€', false)

ON CONFLICT (slug) DO NOTHING;

-- ================================================================
-- BATCH 3 — L (resto) → P
-- ================================================================

INSERT INTO maison (nome, slug, tipo, zona_id, sede_comune, sede_regione, sede_indirizzo, telefono, sito_web, anno_fondazione, proprieta, gruppo, direzione, chef_de_cave, ettari_totali, ettari_proprieta, ettari_gestione, pct_pinot_noir, pct_chardonnay, pct_meunier, certificazioni, tipo_pressa, vinificazione, malolattica, produzione_bottiglie, stock_cantina, importatore_italia, visita_possibile, degustazione_possibile, descrizione, filosofia, fascia_prezzo, is_free) VALUES

('Lucien Collard', 'lucien-collard', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Bouzy', 'Marne', NULL, NULL, NULL, NULL, 'Famille Collard', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 80, 15, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Bouzy, Grand Cru della Montagne de Reims. Champagne da Pinot Noir di grande autenticità e struttura da uno dei crus più celebri per il vitigno.', 'Il Grand Cru Bouzy come terroir di vocazione per il Pinot Noir champenois.', '€€€', false),

('Maillart', 'maillart', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Nanteuil-la-Forêt', 'Marne', NULL, NULL, NULL, NULL, 'Famille Maillart', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 45, 30, 25, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Nanteuil-la-Forêt nella Montagne de Reims occidentale. Champagne di carattere da un terroir meno noto ma di grande personalità, con vigne su suoli calcareo-gessosi.', 'La Montagne de Reims occidentale come territorio di espressione autentica e ancora poco esplorata dalla critica internazionale.', '€€€', false),

('Mailly', 'mailly-cm', 'CM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Mailly-Champagne', 'Marne', '28 Rue de la Libération, 51500 Mailly-Champagne', '+33 3 26 49 41 10', 'www.champagne-mailly.com', 1929, 'Coopérative de Mailly', 'Cooperativa', NULL, 'Hervé Dantan', 75, 75, NULL, 75, 20, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 500000, NULL, NULL, true, false,
 'Cooperativa di eccellenza fondata nel 1929 nel Grand Cru Mailly-Champagne. Produce champagne esclusivamente da uve del proprio Grand Cru, con grande coerenza stilistica. Il Blanc de Noirs e la cuvée Les Échansons sono tra le referenze più apprezzate della cooperativa.', 'Un solo Grand Cru per tutti i vini: la cooperativa di Mailly dimostra che qualità e cooperazione non sono concetti opposti, ma alleati naturali.', '€€€', false),

('Mandois', 'mandois', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Pierry', 'Marne', '66 Rue du Général de Gaulle, 51530 Pierry', '+33 3 26 54 03 18', 'www.champagne-mandois.fr', 1735, 'Famille Mandois', 'Indipendente', 'Claude Mandois', 'Claude Mandois', 30, 30, NULL, 40, 35, 25, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 400000, NULL, NULL, true, true,
 'Maison storica di Pierry fondata nel 1735, tra le più antiche ancora a conduzione familiare della Champagne. Claude Mandois guida l''azienda con champagne di grande eleganza e identità territoriale. Il Victor Mandois millesimato è la cuvée di punta.', 'Quasi tre secoli di storia familiare a Pierry: la continuità come valore supremo e l''eleganza come stile riconoscibile attraverso le generazioni.', '€€€', false),

('Manon Boutillez-Guer', 'manon-boutillez-guer', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Villers-Marmery', 'Marne', NULL, NULL, NULL, NULL, 'Manon Boutillez-Guer', 'Indipendente', 'Manon Boutillez-Guer', 'Manon Boutillez-Guer', NULL, NULL, NULL, 10, 80, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Giovane vigneronne con vigne a Villers-Marmery, Premier Cru atipico della Montagne de Reims dominato da Chardonnay in zona tipicamente a Pinot Noir. Champagne di bella tensione e originalità.', 'La nuova generazione della Montagne de Reims: Chardonnay in un terroir vocato al Pinot Noir per champagne di grande originalità stilistica.', '€€€', false),

('Marc Hébrart', 'marc-hebrart', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Mareuil-sur-Aÿ', 'Marne', '18-20 Rue du Pont, 51160 Mareuil-sur-Aÿ', '+33 3 26 52 60 75', 'www.champagne-hebrart.com', 1964, 'Jean-Paul Hébrart', 'Indipendente', 'Jean-Paul Hébrart', 'Jean-Paul Hébrart', 14, 14, NULL, 50, 45, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox e legno', 'svolta parziale', 100000, NULL, NULL, false, true,
 'Jean-Paul Hébrart è tra i più rispettati vigneron della regione, con vigne tra Mareuil-sur-Aÿ, Aÿ e la Côte des Blancs. I suoi champagne — in particolare la Sélection e il Blanc de Blancs Cuvée de Suzel — esprimono un equilibrio perfetto tra struttura e finezza.', 'L''equilibrio come vocazione: vigne a cavallo tra Montagne de Reims e Côte des Blancs per champagne che coniugano struttura da Pinot Noir e finezza da Chardonnay con rara armonia.', '€€€', false),

('Marie Courtin', 'marie-courtin', 'RM', NULL, 'Polisy', 'Aube', NULL, NULL, NULL, NULL, 'Dominique Moreau', 'Indipendente', 'Dominique Moreau', 'Dominique Moreau', 4, 4, NULL, 90, 5, 5, ARRAY['Biodinamica', 'Demeter']::text[], 'pneumatica', 'botti di rovere usate', 'non svolta', 15000, NULL, 'Vino e Design', false, false,
 'Dominique Moreau produce a Polisy, nell''Aube, champagne naturali di grande profondità e carattere. Spesso senza aggiunta di solforosa, fermentazioni spontanee e vigne biodinamiche. Efflorescence e Resonance sono tra i vini più originali e toccanti di tutta la Champagne.', 'La natura come maestra: biodinamica integrale nell''Aube, fermentazioni spontanee e zero solforosa per champagne che esprimono la purezza di un territorio autentico e fuori dalle convenzioni.', '€€€€', false),

('Matthieu Cugnart', 'matthieu-cugnart', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Villers-sous-Châtillon', 'Marne', NULL, NULL, NULL, NULL, 'Matthieu Cugnart', 'Indipendente', 'Matthieu Cugnart', 'Matthieu Cugnart', NULL, NULL, NULL, 25, 25, 50, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Giovane vigneron di Villers-sous-Châtillon nella Valle della Marna con approccio artigianale. Champagne di carattere che valorizzano il Meunier del territorio.', 'La Valle della Marna e il Meunier come territorio e vitigno di riferimento per una giovane generazione di vigneron.', '€€€', false),

('Maurice Choppin', 'maurice-choppin', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Leuvrigny', 'Marne', NULL, NULL, NULL, NULL, 'Famille Choppin', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 20, 20, 60, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Leuvrigny nella Valle della Marna con champagne di carattere artigianale. Produzione tradizionale con forte identità territoriale.', 'La tradizione vitivinicola della Valle della Marna in tutta la sua autenticità artigianale.', '€€', false),

('Moussé', 'mousse', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Cuisles', 'Marne', '2 Rue Bailly, 51700 Cuisles', '+33 3 26 58 10 80', 'www.champagne-mousse.fr', NULL, 'Cédric Moussé', 'Indipendente', 'Cédric Moussé', 'Cédric Moussé', 7, 7, NULL, 10, 10, 80, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 50000, NULL, 'Vino e Design', false, true,
 'Cédric Moussé è uno dei più grandi interpreti del Pinot Meunier al mondo. I suoi champagne da Cuisles, nella Valle della Marna, dimostrano che il Meunier può raggiungere vette di complessità solitamente attribuite solo a Chardonnay e Pinot Noir. L''Or d''Eugène è un capolavoro assoluto.', 'La riabilitazione del Meunier: Cédric Moussé dimostra che il vitigno più piantato della Champagne, in mani esperte e su terroir vocati, produce champagne di straordinaria complessità e bevibilità.', '€€€', false),

('Odile Thieuillet', 'odile-thieuillet', 'RM', NULL, 'Baroville', 'Aube', NULL, NULL, NULL, NULL, 'Odile Thieuillet', 'Indipendente', 'Odile Thieuillet', 'Odile Thieuillet', NULL, NULL, NULL, 85, 10, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneronne dell''Aube con approccio naturale e champagne di grande carattere da Pinot Noir. Espressione autentica del territorio meridionale della Champagne.', 'Il Pinot Noir dell''Aube da una vigneronne che porta freschezza e autenticità in un territorio ancora poco conosciuto.', '€€€', false),

('Pascal Agrapart', 'pascal-agrapart', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', '57 Avenue Jean Jaurès, 51190 Avize', '+33 3 26 57 51 38', 'www.champagne-agrapart.com', 1894, 'Famille Agrapart', 'Indipendente', 'Pascal Agrapart', 'Pascal e Samuel Agrapart', 10, 10, NULL, 0, 97, 3, ARRAY[]::text[], 'pneumatica', 'botti di rovere usate e acciaio', 'svolta parziale', 70000, NULL, 'Vino e Design', false, true,
 'Pascal Agrapart è uno dei più grandi interpreti della Côte des Blancs. Vigne nei Grand Crus di Avize, Cramant, Oger e Oiry per champagne di straordinaria precisione. Minéral, Terroirs, Vénus, Avizoise e Expérience sono tra i Blanc de Blancs più complessi e ricercati esistenti.', 'Il Grand Cru Côte des Blancs nella sua forma più pura: Pascal Agrapart coniuga rigore tecnico e sensibilità artigianale per champagne che esprimono la quintessenza del Chardonnay champenois.', '€€€€', false),

('Paul Déthune', 'paul-dethune', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Ambonnay', 'Marne', '2 Rue du Moulin, 51150 Ambonnay', '+33 3 26 57 01 88', 'www.champagne-dethune.com', 1880, 'Pierre Déthune', 'Indipendente', 'Pierre Déthune', 'Pierre Déthune', 7, 7, NULL, 80, 15, 5, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta', 60000, NULL, NULL, false, true,
 'Domaine storico di Ambonnay, Grand Cru della Montagne de Reims per eccellenza del Pinot Noir. Pierre Déthune produce champagne di grande struttura con vigne centenarie su suoli calcareo-gessosi. La Cuvée Prestige e il Clos des Moulins sono di rara profondità e longevità.', 'Ambonnay Grand Cru come terroir per il Pinot Noir champenois: vigne centenarie e artigianalità millenaria per champagne di struttura borgognona.', '€€€', false),

('Pertois-Moriset', 'pertois-moriset', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', '2 Place du Général de Gaulle, 51190 Le Mesnil-sur-Oger', '+33 3 26 57 51 40', 'www.champagne-pertois-moriset.com', 1951, 'Famille Pertois', 'Indipendente', NULL, NULL, 12, 12, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 100000, NULL, NULL, false, true,
 'Domaine storico di Le Mesnil-sur-Oger con vigne nei Grand Crus della Côte des Blancs. Blanc de Blancs di grande mineralità gessosa, verticalità e longevità eccezionale da uno dei terroir più illustri della Champagne.', 'Il Le Mesnil-sur-Oger come eredità: decenni di lavoro sullo stesso terroir gessoso per Blanc de Blancs che esprimono la quintessenza del Grand Cru.', '€€€', false),

('Philipponnat', 'philipponnat', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Mareuil-sur-Aÿ', 'Marne', '13 Rue du Pont, 51160 Mareuil-sur-Aÿ', '+33 3 26 56 93 00', 'www.philipponnat.com', 1910, 'Lanson-BCC', 'Lanson-BCC Group', 'Charles Philipponnat', 'Émilien Boutillat', 20, 20, NULL, 55, 35, 10, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 500000, NULL, 'Rinaldi Importatori', true, true,
 'Maison fondata nel 1910, celebre per il Clos des Goisses — 5,5 ettari in forte pendio sul Marne, uno dei clos più iconici e costosi di tutta la Champagne. Charles Philipponnat produce champagne di grande struttura e capacità di invecchiamento con fermentazione parziale in legno.', 'Il Clos des Goisses come vertice: una vigna unica, un microclima eccezionale e decenni di affinamento per champagne che sfidano il tempo e la gravità — letteralmente.', '€€€€', false),

('Pierre Gerbais', 'pierre-gerbais', 'RM', NULL, 'Celles-sur-Ource', 'Aube', '6 Rue de Balnot, 10110 Celles-sur-Ource', '+33 3 25 38 56 59', 'www.champagne-gerbais.fr', NULL, 'Aurélie Gerbais', 'Indipendente', 'Aurélie Gerbais', 'Aurélie Gerbais', 10, 10, NULL, 60, 30, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox e legno', 'svolta parziale', 80000, NULL, 'Vino e Design', false, true,
 'Aurélie Gerbais porta avanti il domaine di famiglia a Celles-sur-Ource nell''Aube con grande personalità. I suoi champagne valorizzano il Pinot Blanc — vitigno rarissimo — accanto al Pinot Noir dell''Aube. L''Origine e il Grains de Celles sono espressioni uniche del territorio.', 'Il Pinot Blanc come tesoro nascosto: Aurélie Gerbais è tra i pochi a valorizzare questo vitigno dimenticato dell''Aube, con champagne di grande originalità e carattere.', '€€€', false),

('Pierre Legras', 'pierre-legras', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Chouilly', 'Marne', NULL, NULL, NULL, NULL, 'Famille Legras', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Chouilly, Grand Cru della Côte des Blancs. Blanc de Blancs di grande eleganza e finezza da un terroir che esprime lo Chardonnay nella sua versione più floreale.', 'Il Grand Cru Chouilly come terroir di elezione per un Blanc de Blancs di grande eleganza e finezza.', '€€€', false),

('Pierre Paillard', 'pierre-paillard', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Bouzy', 'Marne', '2 Rue du 19 Janvier, 51150 Bouzy', '+33 3 26 57 08 04', 'www.champagne-pierre-paillard.com', 1946, 'Antoine e Louis Paillard', 'Indipendente', 'Antoine Paillard', 'Antoine e Louis Paillard', 9, 9, NULL, 70, 25, 5, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 70000, NULL, 'Vino e Design', false, true,
 'Antoine e Louis Paillard gestiscono il domaine di Bouzy con grande rigore e passione. I loro champagne — in particolare Le Mottelette e Les Maillerettes parcellaires — esprimono il Grand Cru Bouzy con profondità e longevità straordinarie. Tra i riferimenti assoluti del movimento vigneron.', 'Il Grand Cru Bouzy attraverso singole parcelle: Antoine e Louis Paillard dimostrano come un territorio già grande possa diventare straordinario quando viene esplorato con la precisione della vigna singola.', '€€€', false),

('Piper-Heidsieck', 'piper-heidsieck', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Reims', 'Marne', '51 Boulevard Henry Vasnier, 51100 Reims', '+33 3 26 84 43 00', 'www.piper-heidsieck.com', 1785, 'Groupe EPI', 'EPI', 'Cyril Lignac (consulente)', 'Emilien Boutillat', NULL, NULL, NULL, 40, 35, 25, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 5000000, NULL, 'Rinaldi Importatori', true, false,
 'Una delle grandi Maison storiche di Reims, fondata nel 1785. La Cuvée Rare Millésimé è considerata tra le prestige cuvée più sottovalutate — e straordinarie — della Champagne per complessità e longevità. Oggi di proprietà EPI, ha ritrovato un''identità stilistica forte sotto la guida di Emilien Boutillat.', 'Il riscatto della grande storia: Piper-Heidsieck riscopre le proprie radici aristocratiche attraverso la Cuvée Rare, uno champagne di profondità e longevità che merita un posto tra le grandi prestige cuvée mondiali.', '€€€', false),

('Pommery', 'pommery', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Reims', 'Marne', '5 Place du Général Gouraud, 51100 Reims', '+33 3 26 61 62 63', 'www.pommery.com', 1858, 'Groupe Vranken', 'Vranken-Pommery', 'Thierry Gasco', 'Thierry Gasco', 300, 300, NULL, 35, 40, 25, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 8000000, NULL, NULL, true, false,
 'Grande Maison di Reims fondata nel 1858. Louise Pommery ha inventato il Brut moderno nel 1874 — prima di lei lo champagne era sempre dolce. Le crayères gallo-romane sotto la Maison, profonde 30 metri e patrimonio UNESCO, ospitano milioni di bottiglie. Il Cuvée Louise è la prestige cuvée di riferimento.', 'L''invenzione del Brut moderno come legacy: Louise Pommery ha cambiato per sempre il mondo dello champagne nel 1874 e le sue crayères romane sono ancora oggi un patrimonio dell''umanità sotto Reims.', '€€€', false),

('Pouillon', 'pouillon', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Mareuil-sur-Aÿ', 'Marne', NULL, NULL, NULL, NULL, 'Famille Pouillon', 'Indipendente', 'Fabrice Pouillon', 'Fabrice Pouillon', NULL, NULL, NULL, 50, 35, 15, ARRAY['HVE']::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Mareuil-sur-Aÿ con approccio biologico e grande attenzione alla sostenibilità in vigna. Champagne di grande bevibilità e carattere territoriale.', 'La sostenibilità come scelta consapevole: viticoltura biologica a Mareuil-sur-Aÿ per champagne autentici e rispettosi dell''ambiente.', '€€€', false)

ON CONFLICT (slug) DO NOTHING;

-- ================================================================
-- BATCH 4 — R → W  +  Delamotte, Salon, Maxence Janisson, Palmer & Co, Erick Schreiber
-- ================================================================

INSERT INTO maison (nome, slug, tipo, zona_id, sede_comune, sede_regione, sede_indirizzo, telefono, sito_web, anno_fondazione, proprieta, gruppo, direzione, chef_de_cave, ettari_totali, ettari_proprieta, ettari_gestione, pct_pinot_noir, pct_chardonnay, pct_meunier, certificazioni, tipo_pressa, vinificazione, malolattica, produzione_bottiglie, stock_cantina, importatore_italia, visita_possibile, degustazione_possibile, descrizione, filosofia, fascia_prezzo, is_free) VALUES

-- ── R ──────────────────────────────────────────────────────────

('R. Faivre', 'r-faivre', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', NULL, 'Marne', NULL, NULL, NULL, NULL, 'Famille Faivre', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 50, 30, 20, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Piccolo vigneron della Montagne de Reims con champagne di carattere artigianale. Produzione in piccole quantità con forte identità territoriale e rispetto per la tradizione champenoise.', 'L''artigianalità come scelta: champagne autentici da un piccolo récoltant della Montagne de Reims.', '€€', false),

('Rare Champagne', 'rare-champagne', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Reims', 'Marne', '51 Boulevard Henry Vasnier, 51100 Reims', NULL, 'www.rarechampagne.com', 2019, 'Groupe EPI', 'EPI', NULL, 'Émilien Boutillat', NULL, NULL, NULL, 40, 45, 15, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', NULL, NULL, NULL, false, false,
 'Nata come prestige cuvée di Piper-Heidsieck nel 1976, Rare Champagne è stata rilanciata come marchio autonomo nel 2019. Produce solo due referenze: Rare Millésimé Blanc e Rare Millésimé Rosé, entrambi di straordinaria profondità e complessità da annate eccezionali con lungo affinamento. Tra le prestige cuvée più sottovalutate dalla critica internazionale.', 'Due soli vini, di eccellenza assoluta: la selezione massimale dei vins de base e l''affinamento prolungato come condizioni irrinunciabili per cuvée che sfidano il tempo.', '€€€€', false),

('Régis Poissinet', 'regis-poissinet', 'RM', NULL, 'Essoyes', 'Aube', NULL, NULL, NULL, NULL, 'Régis Poissinet', 'Indipendente', 'Régis Poissinet', 'Régis Poissinet', 7, 7, NULL, 70, 15, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox e legno', 'svolta parziale', 40000, NULL, 'Vino e Design', false, true,
 'Vigneron dell''Aube con approccio sperimentale e curiosità intellettuale rara. Régis Poissinet lavora con Pinot Noir ma soprattutto valorizza vitigni antichi rarissimi come l''Arbane — sopravvissuto solo in pochi ettari della Champagne. I suoi champagne sono originali, profondi e inclassificabili, tra i più discussi del nuovo movimento artigianale.', 'L''Aube come laboratorio: vitigni antichi, metodi naturali e lo spirito del ricercatore per champagne che allargano i confini di ciò che lo champagne può essere.', '€€€', false),

('Rémi Georgeton', 'remi-georgeton', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Verzenay', 'Marne', NULL, NULL, NULL, NULL, 'Rémi Georgeton', 'Indipendente', 'Rémi Georgeton', 'Rémi Georgeton', NULL, NULL, NULL, 80, 15, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Giovane vigneron di Verzenay, Grand Cru della Montagne de Reims. Champagne di grande struttura da Pinot Noir coltivato su suoli calcareo-gessosi in uno dei crus più importanti della regione per il vitigno.', 'Verzenay Grand Cru come terroir di espressione: Pinot Noir di struttura e profondità in un giovane récoltant di grande talento.', '€€€', false),

('Éric Rodez', 'eric-rodez', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Ambonnay', 'Marne', '4 Rue de Isse, 51150 Ambonnay', '+33 3 26 57 04 93', 'www.champagne-ericrodez.com', NULL, 'Éric Rodez', 'Indipendente', 'Éric Rodez', 'Éric Rodez', 6, 6, NULL, 75, 20, 5, ARRAY[]::text[], 'pneumatica', 'botti di rovere usate e acciaio', 'svolta parziale', 55000, NULL, 'Vino e Design', false, true,
 'Éric Rodez è uno dei grandi maestri del Pinot Noir champenois con vigne nel Grand Cru Ambonnay. Botti usate, serbatoi inox, zero filtrazione, dosaggi minimi. Cuvée des Crayères, Empreinte e il Blanc de Noirs sono referenze assolute del movimento vigneron. Cofondatore con David Léclapart del rinnovamento qualitativo dei récoltants champenois.', 'Il Grand Cru Ambonnay con la complessità dei grandi Borgogna: Éric Rodez esprime il Pinot Noir senza compromessi in cantina, per champagne che invecchiano magnificamente.', '€€€', false),

('Roger Brun', 'roger-brun', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Aÿ', 'Marne', '6 Rue des Fossés, 51160 Aÿ', '+33 3 26 54 21 11', 'www.champagne-roger-brun.com', 1773, 'Famille Brun', 'Indipendente', 'Guillaume Brun', 'Guillaume Brun', 7, 7, NULL, 65, 30, 5, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 50000, NULL, NULL, false, true,
 'Una delle famiglie vitivinicole più antiche di Aÿ Grand Cru, con radici documentate al 1773. Guillaume Brun produce champagne di grande struttura da Pinot Noir del Grand Cru Aÿ con vinificazione parziale in legno. Les Cépages, il Blanc de Blancs e i parcellaires completano una gamma di grande coerenza stilistica.', 'Quasi 250 anni di storia ad Aÿ: Guillaume Brun porta avanti una delle eredità familiari più lunghe della Champagne con champagne di struttura classica e identità Grand Cru inconfondibile.', '€€€', false),

('Rousseaux-Batteux', 'rousseaux-batteux', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Verzy', 'Marne', NULL, NULL, NULL, NULL, 'Famille Rousseaux', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 80, 15, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Piccolo vigneron di Verzy, Premier Cru della Montagne de Reims. Champagne di grande carattere da Pinot Noir in uno dei comuni più particolari della regione, celebre per i famosi faux de Verzy — faggi contorti con genetica unica — che danno a questo cru un''aura di singolarità.', 'Verzy e la sua unicità biologica e geologica come ispirazioni per champagne di carattere autentico, fuori dagli schemi commerciali.', '€€€', false),

-- ── S ──────────────────────────────────────────────────────────

('Delamotte', 'delamotte', 'NM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', '7 Rue de la Brèche d''Oger, 51190 Le Mesnil-sur-Oger', '+33 3 26 57 51 65', 'www.salondelamotte.com', 1760, 'Laurent-Perrier', 'Laurent-Perrier Group', 'Didier Depond', 'Didier Depond', NULL, NULL, NULL, 5, 92, 3, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 500000, NULL, 'Pellegrini SpA', true, true,
 'Fondata nel 1760, Delamotte è la maison sorella di Salon — entrambe di proprietà del gruppo Laurent-Perrier con sede a Le Mesnil-sur-Oger. Il Blanc de Blancs de la Côte des Blancs ha una purezza e verticalità gessosa di straordinaria eleganza. Considerata la porta d''ingresso stilistica al mondo di Salon, con lo stesso terroir e la stessa squadra a un prezzo più accessibile.', 'L''eleganza del Mesnil-sur-Oger resa accessibile: Delamotte produce Blanc de Blancs di grande precisione minerale che rispecchiano lo stesso terroir leggendario di Salon.', '€€€', false),

('Salon', 'salon', 'NM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Le Mesnil-sur-Oger', 'Marne', '7 Rue de la Brèche d''Oger, 51190 Le Mesnil-sur-Oger', '+33 3 26 57 51 65', 'www.salondelamotte.com', 1905, 'Laurent-Perrier', 'Laurent-Perrier Group', 'Didier Depond', 'Didier Depond', 1, 1, NULL, 0, 100, 0, ARRAY[]::text[], 'Coquard tradizionale', 'botti di rovere usate', 'svolta', 60000, NULL, 'Pellegrini SpA', true, true,
 'Un solo vino, un solo anno, un solo vitigno, un solo cru. Salon è forse il produttore più leggendario dell''intera Champagne. Fondato da Eugène-Aimé Salon nel 1905, produce esclusivamente Blanc de Blancs da Le Mesnil-sur-Oger Grand Cru solo nelle annate eccezionali — raramente più di 5-6 millesimi per decennio. Un millesimo Salon in cantina è il sogno di ogni collezionista.', 'La perfezione come unico standard: se l''annata non è eccezionale, il vino non viene commercializzato. Un solo vino, un solo villaggio, un solo vitigno, un solo cru — la definizione stessa di vin de terroir.', '€€€€€', false),

('Savart', 'savart', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Écueil', 'Marne', NULL, NULL, NULL, NULL, 'Frédéric Savart', 'Indipendente', 'Frédéric Savart', 'Frédéric Savart', 6, 6, NULL, 60, 35, 5, ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 50000, NULL, 'Vino e Design', false, true,
 'Frédéric Savart è uno dei vigneron più apprezzati dalla critica internazionale. Da Écueil, Premier Cru della Montagne de Reims, produce champagne di grande finezza con vinificazione parziale in legno. L''Ouverture, L''Accomplie e le cuvée parcellaires sono tra i vini più ricercati del movimento artigianale champenois.', 'Écueil Premier Cru come terroir di elezione: Frédéric Savart coniuga rigore tecnico e sensibilità artigianale per champagne di finezza e profondità borgognona.', '€€€', false),

('Stéphane Regnault', 'stephane-regnault', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Oger', 'Marne', NULL, NULL, NULL, NULL, 'Stéphane Regnault', 'Indipendente', 'Stéphane Regnault', 'Stéphane Regnault', NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron della Côte des Blancs con vigne nel Grand Cru Oger. Blanc de Blancs di grande purezza gessosa da uno dei crus più eleganti della regione, meno noto di Avize e Mesnil ma di assoluta classe.', 'Il Grand Cru Oger come terroir di espressione per Blanc de Blancs di grande eleganza e finezza calcarea.', '€€€', false),

('Tarlant', 'tarlant', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Oeuilly', 'Marne', '21 Rue de la Coopérative, 51480 Oeuilly', '+33 3 26 58 30 60', 'www.tarlant.com', 1687, 'Famille Tarlant', 'Indipendente', 'Benoît e Mélanie Tarlant', 'Benoît e Mélanie Tarlant', 14, 14, NULL, 40, 30, 30, ARRAY['HVE']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale', 130000, NULL, 'Vino e Design', false, true,
 'Benoît e Mélanie Tarlant portano avanti una storia familiare straordinaria ad Oeuilly nella Valle della Marna. La gamma Zero (Brut Nature senza dosaggio) è diventata un manifesto per l''intera generazione di champagne naturali. BAM!, La Vigne d''Or, Zero Blanc de Blancs e i singoli clos parcellaires sono tra le espressioni più originali e convincenti del movimento vigneron.', 'Il Brut Nature come filosofia: Benoît e Mélanie Tarlant credono che il grande champagne non abbia bisogno del dosaggio. Ogni vino deve essere abbastanza ricco e complesso da stare in piedi da solo.', '€€€', false),

-- ── V ──────────────────────────────────────────────────────────

('Veuve Fourny', 'veuve-fourny', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Vertus', 'Marne', '5 Rue du Mesnil, 51130 Vertus', '+33 3 26 52 16 30', 'www.champagne-veuve-fourny.com', 1856, 'Charles-Henri et Emmanuel Fourny', 'Indipendente', 'Charles-Henri Fourny', 'Emmanuel Fourny', 9, 9, NULL, 5, 90, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox e legno', 'svolta parziale', 80000, NULL, NULL, false, true,
 'Charles-Henri ed Emmanuel Fourny guidano questo domaine storico di Vertus, Premier Cru della Côte des Blancs. I loro Blanc de Blancs — in particolare Monts Ferrés e le singole vigne di Vertus — esprimono la finezza e la profondità di un Premier Cru che molti considerano degno di Grand Cru. Dosaggi minimi e grande eleganza definiscono lo stile.', 'Vertus Premier Cru come terroir di eccellenza: Charles-Henri ed Emmanuel Fourny dimostrano che il confine tra Premier e Grand Cru è spesso una questione di attenzione e artigianalità, non di suolo.', '€€€', false),

('Vilmart & Cie', 'vilmart', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Rilly-la-Montagne', 'Marne', '4 Rue de la République, 51500 Rilly-la-Montagne', '+33 3 26 03 40 01', 'www.vilmart-champagne.com', 1890, 'Laurent Champs', 'Indipendente', 'Laurent Champs', 'Laurent Champs', 11, 11, NULL, 45, 45, 10, ARRAY[]::text[], 'pneumatica', 'grandi botti di rovere', 'svolta', 100000, NULL, 'Vino e Design', true, true,
 'Laurent Champs è uno dei maestri assoluti della fermentazione in legno in Champagne. A Rilly-la-Montagne, Premier Cru, fermenta tutti i vini in grandi fûts di rovere (228 litri), ottenendo champagne di straordinaria complessità e struttura. Grand Cellier, Grand Cellier d''Or e Cœur de Cuvée sono tra i vini più longevi e raffinati della Montagne de Reims.', 'La quercia come linguaggio: Laurent Champs fermenta in grandi fûts per champagne di complessità borgognona — il legno non si sente ma si percepisce in ogni strato di profondità e persistenza.', '€€€', false),

('Voirin-Jumel', 'voirin-jumel', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Cramant', 'Marne', '777 Rue de la République, 51530 Cramant', '+33 3 26 57 55 22', NULL, NULL, 'Famille Voirin', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, true,
 'Vigneron di Cramant, Grand Cru della Côte des Blancs per eccellenza. Blanc de Blancs di grande purezza e finezza gessosa da uno dei crus più celebri per lo Chardonnay champenois, con una mineralità fragrante e lunghissima.', 'Il Grand Cru Cramant come terroir di vocazione assoluta per Blanc de Blancs di eleganza, mineralità e affilata freschezza.', '€€€', false),

-- ── W ──────────────────────────────────────────────────────────

('Waris-Hubert', 'waris-hubert', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946', 'Avize', 'Marne', NULL, NULL, NULL, NULL, 'Manon Waris', 'Indipendente', 'Manon Waris', 'Manon Waris', NULL, NULL, NULL, 0, 100, 0, ARRAY[]::text[], 'pneumatica', 'acciaio inox e legno', 'svolta parziale', NULL, NULL, NULL, false, false,
 'Manon Waris produce a Avize, Grand Cru della Côte des Blancs, Blanc de Blancs di grande mineralità gessosa. Giovane vigneronne che rappresenta la nuova generazione artigianale femminile della Champagne, con champagne di grande purezza e tensione calcarea.', 'La nuova generazione al Grand Cru Avize: Blanc de Blancs di grande purezza da vigne coltivate con rispetto per la tradizione e sensibilità contemporanea.', '€€€', false),

-- ── Completamento lista ─────────────────────────────────────────

('Maxence Janisson', 'maxence-janisson', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Verzenay', 'Marne', NULL, NULL, NULL, NULL, 'Maxence Janisson', 'Indipendente', 'Maxence Janisson', 'Maxence Janisson', NULL, NULL, NULL, 80, 15, 5, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Giovane vigneron di Verzenay, Grand Cru della Montagne de Reims. Champagne di grande struttura e profondità da Pinot Noir coltivato su suoli calcareo-gessosi di uno dei Grand Crus più importanti per il vitigno.', 'Verzenay Grand Cru come terroir di elezione: Pinot Noir di struttura e bevibilità straordinarie da un giovane récoltant di talento.', '€€€', false),

('Palmer & Co', 'palmer-co', 'CM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc', 'Reims', 'Marne', '67 Rue Jacquart, 51100 Reims', '+33 3 26 07 35 07', 'www.champagne-palmer.fr', 1947, 'Coopérative Palmer', 'Cooperativa', NULL, 'Rémi Vervier', NULL, 390, NULL, 35, 40, 25, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', 2000000, NULL, NULL, true, false,
 'Cooperativa di qualità fondata nel 1947 da sette viticoltori di Reims con vigne nei principali crus della Montagne de Reims. Palmer & Co ha costruito un''identità stilistica riconoscibile con champagne di grande fruibilità e ottimo rapporto qualità-prezzo. Il Blanc de Blancs e i millesimati sono le referenze più apprezzate dalla critica.', 'La cooperativa come strumento di eccellenza: Palmer & Co dimostra che qualità e cooperazione non sono opposti, con champagne di grande accessibilità e carattere genuino.', '€€€', false),

('Réaut', 'reaut', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', NULL, 'Marne', NULL, NULL, NULL, NULL, 'Famille Réaut', 'Indipendente', NULL, NULL, NULL, NULL, NULL, 40, 30, 30, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Piccolo vigneron della Valle della Marna con champagne di carattere artigianale. Produzione in piccole quantità con forte identità territoriale e approccio familiare alla viticoltura champenoise.', 'Artigianalità autentica e rispetto per il terroir della Valle della Marna.', '€€', false),

('Erick Schreiber', 'erick-schreiber', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Mareuil-sur-Aÿ', 'Marne', NULL, NULL, NULL, NULL, 'Erick Schreiber', 'Indipendente', 'Erick Schreiber', 'Erick Schreiber', NULL, NULL, NULL, 50, 40, 10, ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta', NULL, NULL, NULL, false, false,
 'Vigneron di Mareuil-sur-Aÿ con approccio artigianale e champagne di carattere territoriale. Produzione in piccole quantità con vigne nel Premier Cru con forte identità legata alla Valle della Marna e alla Montagne de Reims.', 'L''artigianalità come risposta all''industrializzazione: champagne autentici da vigne di Mareuil-sur-Aÿ lavorate con cura familiare.', '€€€', false),

-- ── Aggiunte extra ──────────────────────────────────────────────

('Bourgeois-Diaz', 'bourgeois-diaz', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972', 'Vandières', 'Marne', NULL, NULL, NULL, NULL, 'Sébastien Bourgeois e Equiné Diaz', 'Indipendente', 'Sébastien Bourgeois', 'Sébastien Bourgeois', 3, 3, NULL, 50, 20, 30, ARRAY['Biologico']::text[], 'pneumatica', 'botti di rovere usate e acciaio', 'non svolta', 15000, NULL, 'Vino e Design', false, true,
 'Sébastien Bourgeois ed Equiné Diaz producono a Vandières, nella Valle della Marna, champagne naturali di grande autenticità. Solfiti bassissimi, fermentazioni spontanee, nessuna filtrazione né chiarifica. I loro vini esprimono il territorio con una purezza rara, avvicinandoli ai migliori vins naturels della Francia. Domaine minuscolo ma con una reputazione crescente tra gli appassionati del genere.', 'Lo champagne come vino naturale: zero interventi in cantina, solfiti minimi e rispetto totale per i ritmi della vigna per ottenere espressioni di terroir autentiche e commoventi.', '€€€', false)

ON CONFLICT (slug) DO NOTHING;
