-- ================================================================
-- CUVÉE — Nuovi Produttori (seconda tornata, ~60 maison)
-- Eseguire nel SQL Editor di Supabase
-- Zone IDs:
--   Vallée de la Marne  = 08daee1e-4c45-4961-9e87-d20c6bac0972
--   Montagne de Reims   = 49ed27e0-9859-431a-ab6c-15a7a6ed13cc
--   Côte des Blancs     = 91b7c08e-b280-4172-a43b-8d9c886df946
--   Côte des Bar / Aube = NULL
-- ================================================================

INSERT INTO maison (
  nome, slug, tipo, zona_id,
  sede_comune, sede_regione, sede_indirizzo, telefono, sito_web,
  anno_fondazione, proprieta, gruppo, direzione, chef_de_cave,
  ettari_totali, ettari_proprieta, ettari_gestione,
  pct_pinot_noir, pct_chardonnay, pct_meunier,
  certificazioni, tipo_pressa, vinificazione, malolattica,
  produzione_bottiglie, stock_cantina, importatore_italia,
  visita_possibile, degustazione_possibile,
  descrizione, filosofia, fascia_prezzo, is_free
) VALUES

-- ── MONTAGNE DE REIMS ─────────────────────────────────────────

('Benoît Marguet', 'benoit-marguet', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Ambonnay', 'Marne', NULL, '+33 3 26 57 01 08', 'www.champagne-marguet.fr',
 NULL, 'Benoît Marguet', 'Indipendente', 'Benoît Marguet', 'Benoît Marguet',
 9, 9, NULL, 75, 20, 5,
 ARRAY['Biodinamica','Demeter']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 60000, NULL, NULL, false, true,
 'Benoît Marguet è uno dei vigneron biodinamici più rigorosi della Champagne. Con vigne nei Grand Crus di Ambonnay e Bouzy, certificato Demeter dal 2013, produce champagne di profondità straordinaria e tensione naturale. Ogni cuvée — Shaman, Sapience, Benoît Marguet Brut Nature — racconta il terroir gessoso con una purezza difficilmente eguagliabile.',
 'Biodinamica profonda e Demeter come unica via: le vigne di Ambonnay e Bouzy coltivate con rispetto totale per il ciclo naturale producono champagne di rara autenticità e complessità.',
 '€€€€', false),

('Marie-Noëlle Ledru', 'marie-noelle-ledru', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Ambonnay', 'Marne', NULL, NULL, NULL,
 NULL, 'Marie-Noëlle Ledru', 'Indipendente', 'Marie-Noëlle Ledru', 'Marie-Noëlle Ledru',
 3, 3, NULL, 85, 10, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 25000, NULL, NULL, false, true,
 'Marie-Noëlle Ledru è una delle figure più rispettate tra i piccoli récoltants in Champagne. Le sue vigne ad Ambonnay Grand Cru, con vecchie viti di Pinot Noir, producono champagne di grande struttura, autenticità e longevità. Il Cuvée du Goulté millesimato è tra i Blanc de Noirs più ricercati dai conoscitori internazionali.',
 'La tradizione come forza: Ambonnay Grand Cru attraverso vecchie viti di Pinot Noir coltivate con rispetto per il territorio e vinificate con rigore artigianale.',
 '€€€', false),

('Pehu-Simonet', 'pehu-simonet', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Verzenay', 'Marne', NULL, NULL, 'www.champagne-pehu-simonet.com',
 NULL, 'Famille Pehu-Simonet', 'Indipendente', NULL, NULL,
 8, 8, NULL, 80, 15, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 60000, NULL, NULL, false, true,
 'Vigneron di Verzenay, uno dei Grand Crus più celebri della Montagne de Reims per il Pinot Noir. Pehu-Simonet produce champagne di grande struttura e profondità, con una gamma che include Blanc de Noirs e millesimati di grande carattere. Il Grand Cru Verzenay è il cuore pulsante di ogni bottiglia.',
 'Verzenay Grand Cru come identità: il Pinot Noir su suoli gessosi profondi espresso con eleganza e struttura da un domaine familiare radicato nel territorio da generazioni.',
 '€€€', false),

('Jean Lallement', 'jean-lallement', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Verzenay', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Lallement', 'Indipendente', NULL, NULL,
 4, 4, NULL, 90, 10, 0,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 30000, NULL, NULL, false, true,
 'Piccolo vigneron di Verzenay Grand Cru con vigne centenarie di Pinot Noir. Jean Lallement produce champagne di rara concentrazione e autenticità, con una produzione limitatissima che ne fa uno dei produttori più ricercati dagli amatori. Il Brut Réserve Grand Cru è un classico intramontabile per chi ama il Pinot Noir nella sua espressione più austera.',
 'Purezza e autenticità: vigne vecchie di Verzenay Grand Cru per champagne di struttura e longevità eccezionali, prodotti senza compromessi con la tradizione artigianale più rigorosa.',
 '€€€', false),

('Godmé', 'godme', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Verzenay', 'Marne', NULL, '+33 3 26 49 00 64', 'www.champagne-godme.fr',
 NULL, 'Hugues Godmé', 'Indipendente', 'Hugues Godmé', 'Hugues Godmé',
 9, 9, NULL, 70, 25, 5,
 ARRAY['HVE']::text[], 'pneumatica', 'acciaio inox', 'svolta',
 70000, NULL, NULL, false, true,
 'Hugues Godmé conduce con cura e rigore il suo domaine a Verzenay, Grand Cru della Montagne de Reims. Produttore impegnato nella viticoltura sostenibile con certificazione HVE, esprime il Pinot Noir e gli assemblaggi Grand Cru con grande chiarezza territoriale. Le Vieilles Vignes Grand Cru è l''espressione più alta del domaine.',
 'Sostenibilità e Grand Cru Verzenay: Hugues Godmé interpreta il Pinot Noir con rigore e sensibilità ambientale, valorizzando ogni parcella con approccio artigianale e rispetto per l''ecosistema viticolo.',
 '€€€', false),

('Nicolas Maillart', 'nicolas-maillart', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Écueil', 'Marne', NULL, '+33 3 26 49 77 84', 'www.champagne-nicolas-maillart.fr',
 NULL, 'Nicolas Maillart', 'Indipendente', 'Nicolas Maillart', 'Nicolas Maillart',
 11, 11, NULL, 55, 30, 15,
 ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 60000, NULL, NULL, false, true,
 'Nicolas Maillart ha convertito il suo domaine alla biodinamica trasformandolo in uno dei riferimenti del Premier Cru Écueil. Con vigne su suoli argillo-calcarei ricchi di fossili, produce champagne di grande precisione e profondità, con basse solforazioni e fermentazioni native. Il Platine Premier Cru è la sua bottiglia simbolo.',
 'Biodinamica al Premier Cru: Écueil come terroir di elezione per champagne di profondità e complessità, prodotti con rispetto totale per il ciclo naturale della vigna.',
 '€€€', false),

('Emmanuel Brochet', 'emmanuel-brochet', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Villedommange', 'Marne', NULL, NULL, NULL,
 NULL, 'Emmanuel Brochet', 'Indipendente', 'Emmanuel Brochet', 'Emmanuel Brochet',
 4, 4, NULL, 60, 35, 5,
 ARRAY[]::text[], 'pneumatica', 'botti di rovere usate', 'svolta parziale',
 20000, NULL, 'Vino e Design', false, true,
 'Emmanuel Brochet è uno dei récoltants più affascinanti e meno conosciuti della Montagne de Reims. Il suo domaine a Villedommange produce in quantità minime champagne di grande tensione e bevibilità, con vinificazioni in legno e zero interventi superflui. Le Mont Benoit, la sua cuvée più rappresentativa, è champagne vigneron allo stato puro.',
 'Minimalismo produttivo e massima espressività: poche bottiglie, massima cura, nessun compromesso per champagne che parlano direttamente del terroir di Villedommange attraverso il legno e la naturalezza.',
 '€€€€', false),

('J. Lassalle', 'j-lassalle', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Chigny-les-Roses', 'Marne', NULL, '+33 3 26 03 42 19', 'www.champagne-jlassalle.com',
 1942, 'Famille Lassalle', 'Indipendente', NULL, NULL,
 11, 11, NULL, 45, 35, 20,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 100000, NULL, NULL, false, true,
 'Storica maison familiare di Chigny-les-Roses, Premier Cru della Montagne de Reims. J. Lassalle produce champagne di grande eleganza e accessibilità, con la Cuvée Angéline e il Premier Cru millesimato come referenze principali. Oggi condotta dalla terza generazione della famiglia con costante attenzione alla qualità e alla coerenza stilistica.',
 'Tradizione e continuità: tre generazioni della famiglia Lassalle al servizio del Premier Cru Chigny-les-Roses per champagne di eleganza classica e grande affidabilità.',
 '€€€', false),

('Margaine', 'margaine', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Villers-Marmery', 'Marne', NULL, '+33 3 26 97 92 13', NULL,
 NULL, 'Famille Margaine', 'Indipendente', NULL, NULL,
 6, 6, NULL, 5, 90, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 50000, NULL, NULL, false, true,
 'Vigneron di Villers-Marmery, un Premier Cru unico nella Montagne de Reims: l''unico villaggio della zona con vocazione prevalente allo Chardonnay, oltre il 90% delle vigne. Margaine produce Blanc de Blancs di grande finezza e mineralità, una rarità assoluta nella Montagne de Reims dominata dal Pinot Noir.',
 'L''eccezione nella Montagne de Reims: Villers-Marmery come enclave di Chardonnay in un territorio di Pinot Noir, per Blanc de Blancs di rara finezza e identità geografica unica.',
 '€€€', false),

('Gratiot-Pillière', 'gratiot-pilliere', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Trépail', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Gratiot-Pillière', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 10, 85, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Vigneron di Trépail, Premier Cru della Montagne de Reims con forte vocazione allo Chardonnay. Gratiot-Pillière produce champagne di grande freschezza e finezza calcarea da un terroir ancora poco valorizzato ma di grande potenziale qualitativo, destinato alla scoperta da parte degli appassionati.',
 'Trépail Premier Cru come terroir di Chardonnay nella Montagne de Reims: freschezza, mineralità e identità in champagne artigianali di carattere autentico e ancora accessibile.',
 '€€€', false),

('Collery', 'collery', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Aÿ', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Collery', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 80, 15, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Vigneron di Aÿ, Grand Cru tra i più rinomati per il Pinot Noir champenois. Collery produce champagne di struttura e profondità da uno dei terroir storicamente più apprezzati per il vitigno. Piccola produzione artigianale con forte radici territoriali in uno dei comuni simbolo della Champagne.',
 'Il Grand Cru Aÿ come vocazione assoluta: Pinot Noir di struttura e carattere in produzioni limitate che esaltano uno dei terroir più prestigiosi e storicamente significativi della regione.',
 '€€€', false),

('Cattier', 'cattier', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Chigny-les-Roses', 'Marne', '6-11 Rue Dom Pérignon, 51500 Chigny-les-Roses', '+33 3 26 03 42 11', 'www.cattier.com',
 1918, 'Famille Cattier', 'Indipendente', 'Jean-Louis e Alexandre Cattier', NULL,
 33, 33, NULL, 50, 30, 20,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 500000, NULL, NULL, true, true,
 'Maison familiare fondata nel 1918 a Chigny-les-Roses, Premier Cru della Montagne de Reims. Cattier è nota per il Clos du Moulin, uno dei pochissimi clos murati della Champagne — una vigna di 2,2 ettari Premier Cru di straordinaria continuità storica. È anche la maison che produce la celebre Armand de Brignac, la "Ace of Spades" di fama internazionale.',
 'Il Clos du Moulin come patrimonio unico: una vigna murata Premier Cru tra le rarità assolute della Champagne, prodotta con rigore artigianale da quattro generazioni della stessa famiglia.',
 '€€€', false),

('Barnaut', 'barnaut', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Bouzy', 'Marne', NULL, '+33 3 26 57 01 54', 'www.champagnebarnaut.com',
 NULL, 'Famille Barnaut', 'Indipendente', NULL, NULL,
 12, 12, NULL, 85, 10, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 90000, NULL, NULL, false, true,
 'Vigneron storico di Bouzy, Grand Cru della Montagne de Reims. Barnaut produce champagne di grande struttura e autenticità da uno dei comuni più celebri per il Pinot Noir champenois. Le vigne vecchie danno ai vini una concentrazione e profondità particolari, con il Grand Cru millesimato come referenza di punta.',
 'Bouzy Grand Cru come terroir d''eccellenza: vigne vecchie di Pinot Noir per champagne di struttura autentica e grande identità territoriale in un produttore familiare di solida reputazione.',
 '€€€', false),

('Camille Saves', 'camille-saves', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Bouzy', 'Marne', '4 Rue de Condé, 51150 Bouzy', '+33 3 26 57 00 33', NULL,
 NULL, 'Famille Saves', 'Indipendente', NULL, NULL,
 9, 9, NULL, 80, 15, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 70000, NULL, NULL, false, true,
 'Vigneron tradizionale di Bouzy, Grand Cru della Montagne de Reims. Camille Saves produce champagne classici da Pinot Noir con una gamma affidabile e di carattere autentico. Il Grand Cru Brut millesimato e il Rosé de Bouzy sono le referenze più apprezzate di un domaine che esprime Bouzy con coerenza e rispetto.',
 'La tradizione di Bouzy Grand Cru nella sua espressione più autentica: Pinot Noir coltivato con cura familiare per champagne di struttura e continuità stilistica che non tradisce mai.',
 '€€€', false),

('Bernard Remy', 'bernard-remy', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Chigny-les-Roses', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Remy', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 45, 35, 20,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Vigneron di Chigny-les-Roses, Premier Cru della Montagne de Reims. Bernard Remy produce champagne di carattere artigianale con forte identità territoriale, valorizzando le diverse varietà del Premier Cru in assemblaggi equilibrati e di grande bevibilità quotidiana.',
 'Il Premier Cru Chigny-les-Roses come terroir di riferimento per champagne artigianali di carattere autentico e bevibilità immediata.',
 '€€€', false),

('Philippart', 'philippart', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Chigny-les-Roses', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Philippart', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 50, 30, 20,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Piccolo vigneron di Chigny-les-Roses nel cuore del Premier Cru della Montagne de Reims. Philippart produce champagne di carattere autentico con forte radicamento territoriale, valorizzando le diverse varietà del Premier Cru in produzioni limitate di qualità artigianale.',
 'Artigianalità e territorio: il Premier Cru Chigny-les-Roses come punto di partenza per champagne autentici prodotti con metodo familiare e rispetto per la vigna.',
 '€€€', false),

('Francis Orban', 'francis-orban', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Sacy', 'Marne', NULL, NULL, NULL,
 NULL, 'Francis Orban', 'Indipendente', 'Francis Orban', 'Francis Orban',
 NULL, NULL, NULL, 50, 30, 20,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Vigneron di Sacy, Premier Cru della Montagne de Reims occidentale. Francis Orban produce champagne di carattere con forte identità territoriale, valorizzando un cru meno conosciuto ma di grande personalità su suoli argillo-calcarei ricchi di fossili marini.',
 'Sacy Premier Cru come terroir di scoperta: champagne artigianali da un vigneron che valorizza un territorio autentico e ancora poco esplorato dagli appassionati internazionali.',
 '€€€', false),

('Sadi Malot', 'sadi-malot', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Villers-Marmery', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Malot', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 10, 85, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Vigneron di Villers-Marmery, Premier Cru della Montagne de Reims con vocazione prevalente allo Chardonnay. Sadi Malot produce Blanc de Blancs di grande finezza in un terroir che fa eccezione nella zona dominata dal Pinot Noir — un produttore da scoprire per chi ama la purezza del Chardonnay champenois in contesti inattesi.',
 'La sorpresa della Montagne de Reims: Chardonnay di grande finezza da Villers-Marmery, un Premier Cru che sfida la logica geografica con eleganza e precisione.',
 '€€€', false),

-- ── VALLÉE DE LA MARNE ────────────────────────────────────────

('Christophe Mignon', 'christophe-mignon', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Festigny', 'Marne', NULL, '+33 3 26 58 35 44', 'www.christophe-mignon.com',
 NULL, 'Christophe Mignon', 'Indipendente', 'Christophe Mignon', 'Christophe Mignon',
 8, 8, NULL, 5, 10, 85,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale',
 60000, NULL, NULL, false, true,
 'Christophe Mignon è tra i più appassionati interpreti del Pinot Meunier nella Valle della Marna. I suoi champagne Pur Meunier esprimono con rara chiarezza il carattere fruttato e la profondità di un vitigno troppo spesso sottovalutato. A Festigny, su suoli argillosi della Valle della Marna, il Meunier rivela una complessità inaspettata e commovente.',
 'Il Meunier come missione: Festigny come terroir di elezione per un vitigno che in mani capaci esprime freschezza, profondità e un carattere del tutto proprio, irripetibile altrove.',
 '€€€', false),

('Françoise Bedel', 'francoise-bedel', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Crouttes-sur-Marne', 'Marne', '71 Route de Château-Thierry, 02310 Crouttes-sur-Marne', '+33 3 23 82 15 80', 'www.francoise-bedel.com',
 NULL, 'Françoise Bedel', 'Indipendente', 'Françoise e Antoine Bedel', 'Françoise Bedel',
 9, 9, NULL, 5, 10, 85,
 ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 70000, NULL, NULL, false, true,
 'Françoise Bedel è una delle pioniere della biodinamica in Champagne, con una conversione iniziata nei primi anni ''90. Il suo domaine a Crouttes-sur-Marne nella Valle della Marna produce champagne da Meunier con solfiti minimi, fermentazioni spontanee e grande rispetto per i cicli lunari. L''Âme de la Terre è la sua cuvée più emblematica.',
 'La biodinamica come stile di vita: Françoise Bedel ha trasformato il Pinot Meunier della Valle della Marna in un''espressione di rispetto totale per la terra, con champagne di purezza e profondità rare.',
 '€€€€', false),

('Lelarge-Pugeot', 'lelarge-pugeot', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Vrigny', 'Marne', NULL, NULL, 'www.champagne-lelarge-pugeot.com',
 NULL, 'Famille Lelarge-Pugeot', 'Indipendente', NULL, NULL,
 7, 7, NULL, 25, 25, 50,
 ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 40000, NULL, NULL, false, true,
 'Domaine biodinamico di Vrigny, Premier Cru noto per la sua singolare composizione con tutti e tre i vitigni champenois in proporzioni equilibrate. Lelarge-Pugeot lavora le vigne con rigore biodinamico e produce champagne di grande bevibilità ed equilibrio, espressione autentica di un cru spesso trascurato ma di grande personalità.',
 'Biodinamica e il Premier Cru Vrigny: un terroir di grande personalità dove i tre vitigni champenois trovano espressione armoniosa in champagne di bevibilità naturale e autenticità territoriale.',
 '€€€', false),

('Benoît Déhu', 'benoit-dehu', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Festigny', 'Marne', NULL, NULL, NULL,
 NULL, 'Benoît Déhu', 'Indipendente', 'Benoît Déhu', 'Benoît Déhu',
 5, 5, NULL, 5, 10, 85,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale',
 30000, NULL, 'Vino e Design', false, true,
 'Benoît Déhu è un giovane vigneron di Festigny che ha fatto del Pinot Meunier naturale la sua bandiera. I suoi champagne — La Rue des Noyers, Les Parcelles — sono vini di grande freschezza e autenticità, con approccio naturale e bassa solforosa. Uno dei nomi emergenti più interessanti nella Valle della Marna.',
 'Il Meunier naturale di Festigny: Benoît Déhu interpreta il vitigno della Valle della Marna con approccio naturale e grande rispetto per la biodiversità, producendo champagne di vitalità immediata e straordinaria.',
 '€€€', false),

('Dehours', 'dehours', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Cerseuil', 'Marne', NULL, '+33 3 26 52 71 75', 'www.champagne-dehours.fr',
 NULL, 'Jérôme Dehours', 'Indipendente', 'Jérôme Dehours', 'Jérôme Dehours',
 10, 10, NULL, 30, 20, 50,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox e botti di rovere', 'svolta parziale',
 80000, NULL, NULL, false, true,
 'Jérôme Dehours conduce il suo domaine a Cerseuil con approccio attento e rispettoso del terroir. La sua gamma valorizza il Pinot Meunier della Valle della Marna attraverso singole parcelle, con particolare attenzione alla biodiversità e all''artigianalità. Il Grande Réserve esprime l''assemblaggio classico champenois con grande equilibrio.',
 'Parcelle e biodiversità nella Valle della Marna: Jérôme Dehours esplora le sfumature del terroir di Cerseuil attraverso il Meunier con approccio artigianale e grande sensibilità per la natura.',
 '€€€', false),

('Nowack', 'nowack', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Vandières', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Nowack', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 30, 20, 50,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Piccolo vigneron di Vandières nella Valle della Marna, comune noto per la sua posizione centrale nella zona con suoli argillo-calcarei di grande vocazione. Nowack produce champagne di carattere artigianale con forte identità territoriale, valorizzando le diverse varietà della Valle della Marna.',
 'L''autenticità di Vandières: champagne artigianali che esprimono il carattere della Valle della Marna con semplicità e rispetto totale per il territorio.',
 '€€€', false),

('Stroebel', 'stroebel', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Jonquery', 'Marne', NULL, NULL, 'www.champagne-stroebel.com',
 NULL, 'Famille Stroebel', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 20, 15, 65,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale',
 NULL, NULL, NULL, false, false,
 'Vigneron di Jonquery nella Valle della Marna con approccio naturale e champagne da Pinot Meunier di grande autenticità. Stroebel lavora le vigne con rispetto per la biodiversità e produce champagne che esprimono il carattere del terroir della Valle con vivacità, freschezza e immediata bevibilità.',
 'Il terroir di Jonquery attraverso il Meunier: champagne di autenticità naturale che valorizzano un comune poco noto ma ricco di personalità nella Valle della Marna.',
 '€€€', false),

('Jacky Charpentier', 'jacky-charpentier', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Villers-sous-Châtillon', 'Marne', NULL, '+33 3 26 58 05 78', NULL,
 NULL, 'Famille Charpentier', 'Indipendente', NULL, NULL,
 15, 15, NULL, 30, 20, 50,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 100000, NULL, NULL, false, true,
 'Vigneron storico di Villers-sous-Châtillon, uno dei comuni chiave della Valle della Marna per il Pinot Meunier. Jacky Charpentier produce champagne di grande bevibilità e carattere autentico, con una gamma che comprende assemblaggi equilibrati e singoli crus che valorizzano il vitigno tipico della zona.',
 'La tradizione della Valle della Marna: Villers-sous-Châtillon come terroir di eccellenza per il Meunier, interpretato con sapienza familiare da chi conosce ogni vigna da generazioni.',
 '€€€', false),

('José Michel', 'jose-michel', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Moussy', 'Marne', NULL, '+33 3 26 54 06 53', NULL,
 NULL, 'Famille Michel', 'Indipendente', NULL, NULL,
 22, 22, NULL, 20, 20, 60,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 150000, NULL, NULL, false, true,
 'Vigneron storico di Moussy, piccolo comune vicino a Épernay. José Michel è noto per i suoi champagne da Pinot Meunier di grande personalità e longevità, prodotti con metodi tradizionali e profondo rispetto per la vigna. Il Brut Tradition e lo Special Club sono tra le referenze più apprezzate e affidabili del domaine.',
 'Moussy e il Meunier come vocazione storica: José Michel produce da decenni champagne di carattere autentico con il vitigno tipico della Valle della Marna come protagonista principale.',
 '€€€', false),

('Rémi Henry', 'remi-henry', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Fleury-la-Rivière', 'Marne', NULL, NULL, NULL,
 NULL, 'Rémi Henry', 'Indipendente', 'Rémi Henry', 'Rémi Henry',
 NULL, NULL, NULL, 20, 15, 65,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale',
 NULL, NULL, NULL, false, false,
 'Giovane vigneron di Fleury-la-Rivière nella Valle della Marna con approccio naturale e champagne da Meunier di grande freschezza e bevibilità. Rémi Henry rappresenta una nuova generazione di récoltants che valorizzano il territorio con rispetto per la natura e sensibilità artigianale senza compromessi.',
 'La nuova generazione della Valle della Marna: Rémi Henry interpreta il Meunier di Fleury-la-Rivière con freschezza e naturalezza, esprimendo un terroir ancora poco conosciuto ma ricco di potenziale.',
 '€€€', false),

('Caillez-Lemaire', 'caillez-lemaire', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Damery', 'Marne', NULL, '+33 3 26 58 01 78', 'www.champagne-caillez-lemaire.com',
 NULL, 'Famille Caillez-Lemaire', 'Indipendente', NULL, NULL,
 12, 12, NULL, 30, 30, 40,
 ARRAY['HVE']::text[], 'pneumatica', 'acciaio inox', 'svolta',
 80000, NULL, NULL, false, true,
 'Vigneron di Damery nella Valle della Marna con approccio impegnato nella sostenibilità e certificazione HVE (Haute Valeur Environnementale). Caillez-Lemaire produce champagne di carattere territoriale con una gamma equilibrata che valorizza le diverse sfaccettature del terroir di Damery con coerenza e qualità.',
 'Sostenibilità e tradizione a Damery: Caillez-Lemaire coniuga rispetto ambientale e artigianalità champenoise per champagne di identità autentica e grande bevibilità quotidiana.',
 '€€€', false),

('Jean-Noël Haton', 'jean-noel-haton', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Damery', 'Marne', '13 Rue Jean Jaurès, 51480 Damery', '+33 3 26 58 40 45', 'www.champagne-haton.com',
 1960, 'Famille Haton', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 30, 30, 40,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 300000, NULL, NULL, true, true,
 'Maison negociante di Damery nella Valle della Marna, fondata nel 1960 dalla famiglia Haton. Produce champagne di stile classico e grande accessibilità, con una gamma che spazia dal Brut Réserve ai millesimati. Un''istituzione locale apprezzata per la continuità stilistica e il buon rapporto qualità-prezzo.',
 'Lo stile classico della Valle della Marna: Jean-Noël Haton produce champagne di eleganza accessibile con la tradizione negociante come punto di forza e la coerenza qualitativa come missione.',
 '€€€', false),

('Gatinois', 'gatinois', 'RM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Aÿ', 'Marne', NULL, '+33 3 26 55 14 26', NULL,
 NULL, 'Famille Gatinois', 'Indipendente', NULL, NULL,
 7, 7, NULL, 90, 5, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 55000, NULL, NULL, false, true,
 'Vigneron storico di Aÿ, Grand Cru tra i più celebri della Champagne per il Pinot Noir. Gatinois produce champagne di grande struttura e autenticità, con vigne centenarie in uno dei terroir più vocati per il vitigno. Il Grand Cru Brut è un classico di riferimento per chi ama la profondità e l''eleganza del Pinot Noir champenois nella sua espressione più austera.',
 'Aÿ Grand Cru e Pinot Noir come vocazione secolare: Gatinois esprime con sobria eleganza uno dei terroir storicamente più apprezzati dai conoscitori internazionali per la sua profondità e finezza.',
 '€€€', false),

-- ── CÔTE DES BLANCS ───────────────────────────────────────────

('Suenen', 'suenen', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Cramant', 'Marne', NULL, NULL, NULL,
 NULL, 'Aurélien Suenen', 'Indipendente', 'Aurélien Suenen', 'Aurélien Suenen',
 5, 5, NULL, 0, 100, 0,
 ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 30000, NULL, 'Vino e Design', false, true,
 'Aurélien Suenen è uno dei récoltants più ricercati e difficili da trovare della Côte des Blancs. Le sue vigne nel Grand Cru Cramant — e parzialmente a Oger e Chouilly — producono Blanc de Blancs di straordinaria tensione calcarea e complessità. I suoi vini, vinificati in legno con zero interventi, sono tra gli champagne più emozionanti dell''intera regione.',
 'Cramant Grand Cru attraverso il legno e la naturalezza: Aurélien Suenen interpreta lo Chardonnay con una purezza e una profondità che fanno di ogni sua bottiglia un oggetto di culto per i collezionisti di tutto il mondo.',
 '€€€€', false),

('Robert Moncuit', 'robert-moncuit', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Le Mesnil-sur-Oger', 'Marne', '48 Rue de Condé, 51190 Le Mesnil-sur-Oger', '+33 3 26 57 52 71', 'www.champagne-robert-moncuit.com',
 NULL, 'Famille Moncuit', 'Indipendente', 'Pierre Moncuit', 'Pierre Moncuit',
 10, 10, NULL, 0, 100, 0,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 100000, NULL, NULL, false, true,
 'Vigneron del Grand Cru Le Mesnil-sur-Oger con vigne in uno dei terroir più preziosi della Champagne. Robert Moncuit produce Blanc de Blancs di grande mineralità e verticalità calcarea, con la Les Chetillons Vieilles Vignes come cuvée di punta: un''interpretazione magistrale del potenziale di invecchiamento del Mesnil.',
 'Il Mesnil-sur-Oger nella sua essenza più pura: Blanc de Blancs di grande verticalità e tensione calcarea, con vigne vecchie che amplificano la complessità del terroir gessoso leggendario.',
 '€€€', false),

('Guy Larmandier', 'guy-larmandier', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Vertus', 'Marne', NULL, '+33 3 26 52 12 41', NULL,
 NULL, 'Famille Larmandier', 'Indipendente', NULL, NULL,
 11, 11, NULL, 0, 95, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 70000, NULL, NULL, false, true,
 'Vigneron di Vertus, Premier Cru della Côte des Blancs — famiglia diversa dalla più nota Larmandier-Bernier di Vertus. Guy Larmandier produce Blanc de Blancs di grande finezza e carattere calcarea da un terroir profondamente vocato allo Chardonnay, con una continuità stilistica e un''autenticità territoriale di grande affidabilità.',
 'Il Premier Cru Vertus come terroir di Chardonnay: Guy Larmandier produce Blanc de Blancs di eleganza classica e grande bevibilità da vigne ben curate su suoli gessosi della Côte des Blancs.',
 '€€€', false),

('Emmanuel Lassaigne', 'emmanuel-lassaigne', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Montgueux', 'Aube', NULL, '+33 3 25 74 84 41', 'www.champagne-lassaigne.com',
 NULL, 'Emmanuel Lassaigne', 'Indipendente', 'Emmanuel Lassaigne', 'Emmanuel Lassaigne',
 5, 5, NULL, 0, 100, 0,
 ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 30000, NULL, 'Vino e Design', false, true,
 'Emmanuel Lassaigne produce a Montgueux, piccola enclave di Chardonnay su gesso puro vicino a Troyes nell''Aube — un terroir unico e fuori dagli schemi nel panorama champenois. I suoi Blanc de Blancs, vinificati in parte in legno, hanno una tensione calcarea e una verticalità paragonabili ai migliori della Côte des Blancs. Le Cotet, la sua vigna storica, è uno degli champagne più emozionanti e originali della regione.',
 'Montgueux come scoperta assoluta: Chardonnay su gesso puro vicino a Troyes per champagne di mineralità e verticalità rare, un terroir fuori dagli schemi che Emmanuel Lassaigne ha rivelato al mondo con talento e dedizione.',
 '€€€€', false),

('Gimonnet-Oger', 'gimonnet-oger', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Oger', 'Marne', NULL, NULL, NULL,
 NULL, 'Famille Gimonnet', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 0, 100, 0,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Vigneron del Grand Cru Oger nella Côte des Blancs — da non confondere con Pierre Gimonnet & Fils di Cuis. Gimonnet-Oger produce Blanc de Blancs di grande mineralità da uno dei Grand Crus più apprezzati per lo Chardonnay: Oger, con i suoi suoli gessosi particolarmente profondi, dona cremosità e complessità ineguagliabili.',
 'Il Grand Cru Oger come terroir di eccellenza: Blanc de Blancs di mineralità gessosa profonda da un produttore artigianale che valorizza uno dei comuni più vocati della Côte des Blancs.',
 '€€€', false),

('Lombard', 'lombard', 'NM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Épernay', 'Marne', '32 Rue du Général Leclerc, 51200 Épernay', '+33 3 26 55 23 11', 'www.champagne-lombard.com',
 1925, 'Famille Lombard', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 25, 55, 20,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 300000, NULL, NULL, true, true,
 'Maison negociante di Épernay fondata nel 1925, con forte specializzazione nei Blanc de Blancs della Côte des Blancs. Lombard produce champagne di stile elegante e fresco con la Côte des Blancs come territorio di riferimento principale. Una delle maison medie più affidabili e costanti della regione.',
 'La Côte des Blancs come specialità: Lombard produce champagne di eleganza classica con lo Chardonnay come filo conduttore, esprimendo il meglio del terroir calcareo della Côte des Blancs con continuità e stile riconoscibile.',
 '€€€', false),

('Xavier Loriot', 'xavier-loriot', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Villevenard', 'Marne', NULL, NULL, NULL,
 NULL, 'Xavier Loriot', 'Indipendente', 'Xavier Loriot', 'Xavier Loriot',
 6, 6, NULL, 5, 90, 5,
 ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 30000, NULL, NULL, false, true,
 'Xavier Loriot produce a Villevenard nella Côte de Sézanne, una delle zone più interessanti e meno conosciute della Champagne. I suoi Blanc de Blancs da Chardonnay su suoli argillo-calcarei hanno una complessità e una personalità che li distinguono dai più noti crus della Côte des Blancs — più morbidi e fruttati, ma con grande tensione e bevibilità.',
 'La Côte de Sézanne come terroir di scoperta: Xavier Loriot interpreta Villevenard con una freschezza e una complessità che invitano a guardare oltre i Grand Crus più conosciuti.',
 '€€€', false),

('Ulysse Collin', 'ulysse-collin', 'RM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Congy', 'Marne', NULL, NULL, NULL,
 NULL, 'Olivier Collin', 'Indipendente', 'Olivier Collin', 'Olivier Collin',
 5, 5, NULL, 15, 80, 5,
 ARRAY[]::text[], 'pneumatica', 'botti di rovere', 'svolta parziale',
 20000, NULL, 'Vino e Design', false, false,
 'Olivier Collin — che firma le sue bottiglie come Ulysse Collin — è il récoltant più ricercato della Côte de Sézanne. Le sue cuvée da singola parcella — Les Pierrières, Les Maillons, Les Roises — sono tra i champagne più difficili da trovare e più emozionanti dell''intera regione. Vinificati interamente in botte con zero filtrazione, sono un manifesto di purezza e identità.',
 'La Côte de Sézanne come terroir di eccellenza assoluta: Olivier Collin ha dimostrato che Congy può dare champagne da singola vigna tra i più straordinari mai prodotti, con il legno e la naturalezza come strumenti di espressione totale.',
 '€€€€', false),

-- ── CÔTE DES BAR / AUBE ───────────────────────────────────────

('Roses de Jeanne', 'roses-de-jeanne', 'RM', NULL,
 'Celles-sur-Ource', 'Aube', NULL, NULL, NULL,
 NULL, 'Cédric Bouchard', 'Indipendente', 'Cédric Bouchard', 'Cédric Bouchard',
 3, 3, NULL, 95, 5, 0,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'non svolta',
 10000, NULL, 'Vino e Design', false, false,
 'Cédric Bouchard è il vigneron più iconoclasta e radicale dell''Aube. Roses de Jeanne produce una serie di champagne da singola parcella, singolo vitigno, singola annata — senza riserve, senza assemblaggio, senza compromessi. La Haute Lemblé, la Bolorée e le altre cuvée sono oggetti di culto tra i collezionisti mondiali per la loro purezza e immediatezza espressiva.',
 'Un solo vitigno, una sola parcella, un solo millesimo: Cédric Bouchard ha reinventato il concetto di champagne de terroir nell''Aube con una radicalità estetica e qualitativa che lo ha reso leggendario.',
 '€€€€€', false),

('Vouette & Sorbée', 'vouette-et-sorbee', 'RM', NULL,
 'Courteron', 'Aube', NULL, NULL, 'www.vouette-sorbee.com',
 NULL, 'Bertrand Gautherot', 'Indipendente', 'Bertrand Gautherot', 'Bertrand Gautherot',
 5, 5, NULL, 90, 5, 5,
 ARRAY['Biodinamica']::text[], 'pneumatica', 'botti di rovere', 'non svolta',
 25000, NULL, 'Vino e Design', false, true,
 'Bertrand Gautherot gestisce Vouette & Sorbée a Courteron, nell''Aube, con un approccio biodinamico rigoroso e una filosofia naturalista radicale. I suoi champagne — Blanc d''Argile, Fidèle, Saignée de Sorbée — sono vini di grande profondità e purezza, con malolattica non svolta e zero dosaggio come regola assoluta. Tra i produttori naturali più rispettati al mondo.',
 'Biodinamica radicale nell''Aube: Bertrand Gautherot produce champagne naturali di straordinaria purezza con Pinot Noir su suoli kimmeridgiani, esprimendo il terroir con zero compromessi e un coraggio che ha ispirato un''intera generazione di vigneron.',
 '€€€€', false),

('Fleury', 'fleury', 'RM', NULL,
 'Courteron', 'Aube', '43 Grande Rue, 10110 Courteron', '+33 3 25 38 20 28', 'www.champagne-fleury.fr',
 1895, 'Famille Fleury', 'Indipendente', 'Jean-Pierre Fleury', 'Jean-Sébastien Fleury',
 15, 15, NULL, 90, 5, 5,
 ARRAY['Biodinamica','Demeter']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 120000, NULL, NULL, true, true,
 'Fleury è il primo produttore biodinamico di tutta la Champagne, con la conversione iniziata nel 1989 e la certificazione Demeter ottenuta tra i primissimi al mondo per uno champagne. Jean-Pierre Fleury e il figlio Jean-Sébastien gestiscono 15 ettari a Courteron nell''Aube con rigore assoluto. Il Bolero, il Blanc de Noirs e il millesimato Father Fleury sono ambasciatori di una biodinamica vissuta dal 1989.',
 'I pionieri assoluti della biodinamica in Champagne: dal 1989 Fleury dimostra che il Pinot Noir dell''Aube su suoli kimmeridgiani può produrre champagne di straordinaria complessità senza compromettere la natura.',
 '€€€', false),

('Olivier Horiot', 'olivier-horiot', 'RM', NULL,
 'Les Riceys', 'Aube', NULL, '+33 3 25 29 32 16', 'www.champagne-olivier-horiot.fr',
 NULL, 'Olivier Horiot', 'Indipendente', 'Olivier Horiot', 'Olivier Horiot',
 10, 10, NULL, 75, 15, 10,
 ARRAY[]::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 60000, NULL, 'Vino e Design', false, true,
 'Olivier Horiot è il produttore di riferimento di Les Riceys, il comune con tre AOC diverse (Champagne, Rosé des Riceys e Coteaux Champenois). I suoi champagne naturali, con bassa solforosa e vinificazione parziale in legno, esprimono la complessità del Pinot Noir su suoli kimmeridgiani con rara eleganza. Il En Barmont è tra i rosé di macerazione più raffinati dell''Aube.',
 'Les Riceys e la sua triplice vocazione: Olivier Horiot esplora con naturalezza e rispetto le diverse sfaccettature di un terroir straordinario, producendo champagne e rosé di grande autenticità e profondità.',
 '€€€€', false),

('Dosnon', 'dosnon', 'NM', NULL,
 'Avirey-Lingey', 'Aube', NULL, NULL, 'www.champagnedosnon.com',
 NULL, 'Rémi Dosnon', 'Indipendente', 'Rémi Dosnon', 'Rémi Dosnon',
 NULL, NULL, NULL, 85, 10, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta parziale',
 NULL, NULL, NULL, false, true,
 'Rémi Dosnon produce nell''Aube champagne di grande carattere dal Pinot Noir su suoli kimmeridgiani, con approccio attento alla parcella e rispetto per la biodiversità. I suoi vini hanno conquistato la critica internazionale per la loro profondità e personalità inaspettata, contribuendo a rilanciare l''immagine dell''Aube come terroir di eccellenza.',
 'L''Aube attraverso il Pinot Noir di Avirey-Lingey: Dosnon produce champagne di profondità e carattere da un terroir kimmeridgiano che merita più attenzione internazionale di quanta ne abbia ricevuta finora.',
 '€€€€', false),

('Jean Josselin', 'jean-josselin', 'RM', NULL,
 'Gyé-sur-Seine', 'Aube', NULL, '+33 3 25 38 20 89', 'www.champagne-josselin.com',
 NULL, 'Famille Josselin', 'Indipendente', NULL, NULL,
 25, 25, NULL, 90, 5, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 200000, NULL, NULL, true, true,
 'Vigneron di Gyé-sur-Seine nell''Aube con una delle produzioni più consistenti della zona. Jean Josselin valorizza il Pinot Noir su suoli argillo-calcarei tipici dell''Aube con champagne di carattere autentico e grande struttura. Il Blanc de Noirs e i millesimati sono ideali per l''abbinamento gastronomico.',
 'Il Pinot Noir di Gyé-sur-Seine come forza: Jean Josselin produce champagne di struttura e carattere dall''Aube con affidabilità e continuità, punto di riferimento per gli amatori del Pinot Noir champenois.',
 '€€€', false),

('Gremillet', 'gremillet', 'NM', NULL,
 'Essoyes', 'Aube', NULL, '+33 3 25 29 82 51', 'www.champagne-gremillet.fr',
 NULL, 'Famille Gremillet', 'Indipendente', NULL, NULL,
 100, 100, NULL, 85, 10, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 500000, NULL, NULL, true, true,
 'Maison dell''Aube con sede a Essoyes, storico comune dell''Aube noto anche per la presenza del pittore Auguste Renoir. Gremillet gestisce un vigneto di 100 ettari interamente di proprietà con Pinot Noir su suoli kimmeridgiani, producendo champagne di carattere autentico e struttura solida. Il Blanc de Noirs è la referenza principale.',
 'Cento ettari di Pinot Noir nell''Aube: Gremillet produce champagne di struttura e autenticità da uno dei vigneti più estesi della zona, con Essoyes — paese di Renoir — come cuore culturale e viticolo del territorio.',
 '€€€', false),

('Moutard-Diligent', 'moutard-diligent', 'RM', NULL,
 'Buxeuil', 'Aube', 'Rue des Ponts, 10110 Buxeuil', '+33 3 25 38 50 73', 'www.champagne-moutard.fr',
 NULL, 'Famille Moutard', 'Indipendente', NULL, NULL,
 26, 26, NULL, 85, 10, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 200000, NULL, NULL, true, true,
 'Famiglia storica di Buxeuil nell''Aube con tradizione vitivinicola profonda. Moutard-Diligent produce champagne di grande carattere dal Pinot Noir su suoli kimmeridgiani, con una gamma che include anche rarità come il Vieux Marc de Champagne e il Ratafia. Il Cuvée Six Cépages — prodotto da tutti i vitigni della Champagne — è una delle loro creazioni più curiose e originali.',
 'La tradizione completa dell''Aube: Moutard-Diligent produce champagne autentici con radici profonde nel territorio di Buxeuil, valorizzando anche la biodiversità ampelografica con cuvée da vitigni rari e dimenticati.',
 '€€€', false),

('Piollot', 'piollot', 'RM', NULL,
 'Polisy', 'Aube', NULL, NULL, 'www.champagne-piollot.fr',
 NULL, 'Famille Piollot', 'Indipendente', 'Olivier Piollot', 'Olivier Piollot',
 7, 7, NULL, 85, 10, 5,
 ARRAY['Biologico']::text[], 'pneumatica', 'botti di rovere e acciaio', 'svolta parziale',
 40000, NULL, NULL, false, true,
 'Olivier Piollot gestisce il suo piccolo domaine a Polisy nell''Aube con approccio biologico certificato e grande rispetto per la biodiversità. I suoi champagne naturali — con bassa solforosa e fermentazioni spontanee — esprimono il Pinot Noir su suoli kimmeridgiani con una purezza e un''autenticità che ne fanno uno dei produttori naturali più interessanti dell''Aube.',
 'Biologico e naturale nell''Aube: Piollot produce champagne di grande autenticità da Polisy su suoli kimmeridgiani, con un approccio rispettoso della natura che rivela il vero carattere del territorio.',
 '€€€€', false),

('Ruppert-Leroy', 'ruppert-leroy', 'RM', NULL,
 'Essoyes', 'Aube', NULL, NULL, NULL,
 NULL, 'Bénédicte e Emmanuel Leroy', 'Indipendente', 'Bénédicte Leroy', 'Bénédicte Leroy',
 5, 5, NULL, 80, 15, 5,
 ARRAY['Biologico']::text[], 'pneumatica', 'botti di rovere', 'non svolta',
 20000, NULL, 'Vino e Design', false, false,
 'Bénédicte e Emmanuel Leroy producono a Essoyes champagne naturali tra i più ricercati e rari dell''intera Champagne. Con approccio biologico integrale, fermentazioni spontanee, zero dosaggio e solfiti quasi inesistenti, i loro vini — Fosse Grely, Martin Fontaine, Papillon — sono oggetti di culto per gli amatori del vino naturale di qualità assoluta.',
 'Il vino naturale come arte: Ruppert-Leroy produce a Essoyes champagne di purezza assoluta senza compromessi, con il biologico e il minimalismo in cantina come filosofia fondante di ogni singola bottiglia.',
 '€€€€', false),

('Rémy Massin', 'remy-massin', 'NM', NULL,
 'Avirey-Lingey', 'Aube', NULL, '+33 3 25 29 32 25', 'www.champagne-massin.fr',
 NULL, 'Famille Massin', 'Indipendente', NULL, NULL,
 NULL, NULL, NULL, 80, 15, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, true, true,
 'Maison dell''Aube con sede ad Avirey-Lingey, specializzata nel Pinot Noir su suoli kimmeridgiani. Rémy Massin produce champagne di carattere autentico valorizzando il potenziale dell''Aube con una gamma di facile lettura e grande accessibilità. Un riferimento affidabile per chi vuole esplorare la Champagne meridionale.',
 'Il carattere dell''Aube reso accessibile: Rémy Massin produce champagne di Pinot Noir da suoli kimmeridgiani con stile autentico e continuità qualitativa, ambasciatore di un territorio in continua crescita di reputazione.',
 '€€€', false),

('J-M Velut', 'jm-velut', 'RM', NULL,
 'Molins-sur-Aube', 'Aube', NULL, NULL, NULL,
 NULL, 'Jean-Marie Velut', 'Indipendente', 'Jean-Marie Velut', 'Jean-Marie Velut',
 NULL, NULL, NULL, 15, 80, 5,
 ARRAY['Biologico']::text[], 'pneumatica', 'acciaio inox', 'svolta',
 NULL, NULL, NULL, false, false,
 'Jean-Marie Velut produce a Molins-sur-Aube champagne biologici da Chardonnay — una rarità nell''Aube dominata dal Pinot Noir — con approccio rigorosamente certificato bio. I suoi Blanc de Blancs dall''Aube sfidano le convenzioni geografiche offrendo freschezza e mineralità sorprendenti da un terroir insolito per lo Chardonnay champenois.',
 'Chardonnay biologico nell''Aube: J-M Velut sfida le convenzioni producendo Blanc de Blancs certificati bio da Molins-sur-Aube, dimostrando che l''Aube non è solo Pinot Noir e ha ancora molto da rivelare.',
 '€€€', false),

-- ── COOPERATIVE ───────────────────────────────────────────────

('Nicolas Feuillatte', 'nicolas-feuillatte', 'CM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Chouilly', 'Marne', 'Centre Vinicole — Champagne Nicolas Feuillatte, 51530 Chouilly', '+33 3 26 59 55 50', 'www.nicolas-feuillatte.com',
 1972, 'Centre Vinicole de la Champagne', 'Cooperativa', NULL, NULL,
 NULL, NULL, NULL, 30, 40, 30,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 10000000, NULL, NULL, true, false,
 'Nicolas Feuillatte è la più grande cooperativa della Champagne e uno dei marchi più venduti al mondo, con oltre 10 milioni di bottiglie l''anno. Fondata nel 1972 a Chouilly, raggruppa oltre 5.000 viticoltori su tutta la regione. I suoi champagne di stile accessibile e fresco sono il punto d''ingresso per milioni di consumatori nel mondo dello champagne.',
 'Lo champagne per tutti: Nicolas Feuillatte ha democratizzato l''accesso allo champagne di qualità attraverso una cooperativa di scala globale, mantenendo uno stile fresco e riconoscibile accessibile a ogni palato.',
 '€€', false),

('De Saint Gall', 'de-saint-gall', 'CM', '91b7c08e-b280-4172-a43b-8d9c886df946',
 'Avize', 'Marne', '7 Rue Pasteur, 51190 Avize', '+33 3 26 57 94 22', 'www.desaintgall.com',
 1966, 'Union Champagne', 'Cooperativa', NULL, NULL,
 NULL, NULL, NULL, 5, 90, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 2000000, NULL, NULL, true, false,
 'De Saint Gall è il marchio d''eccellenza di Union Champagne, cooperativa fondata nel 1966 ad Avize raccogliendo i vigneron dei Grand Crus della Côte des Blancs. I suoi Blanc de Blancs — in particolare l''Orpale Grand Cru millesimato — sono tra le espressioni cooperative più riuscite della Champagne, con qualità paragonabile a molte maison di lusso.',
 'L''eccellenza cooperativa della Côte des Blancs: De Saint Gall dimostra che la cooperazione tra vigneron dei Grand Crus può produrre champagne di altissimo livello, con l''Orpale millesimato come prova definitiva.',
 '€€€', false),

('Collet', 'collet', 'CM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Aÿ', 'Marne', '34 Rue Jeanson, 51160 Aÿ', '+33 3 26 55 15 88', 'www.champagne-collet.com',
 1921, 'Cogevi', 'Cooperativa', NULL, NULL,
 NULL, NULL, NULL, 40, 35, 25,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 1500000, NULL, NULL, true, true,
 'Cooperativa storica fondata nel 1921 ad Aÿ, uno dei Grand Crus più celebri della Champagne per il Pinot Noir. Collet produce champagne di stile elegante e classico valorizzando il Pinot Noir di Aÿ con una gamma di grande qualità per il segmento cooperativo. La Cuvée Privée e il millesimato Art Deco sono le referenze di punta.',
 'La storia cooperativa di Aÿ: Collet unisce la tradizione del Grand Cru Aÿ con l''efficienza cooperativa per produrre champagne di carattere autentico e stile Art Deco da oltre un secolo.',
 '€€€', false),

('Castelnau', 'castelnau', 'CM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Reims', 'Marne', '5 Rue Gosset, 51100 Reims', '+33 3 26 77 89 00', 'www.champagne-castelnau.com',
 1916, 'Coopérative Régionale des Vins de Champagne', 'Cooperativa', NULL, NULL,
 NULL, NULL, NULL, 35, 40, 25,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 2000000, NULL, NULL, true, false,
 'Cooperativa di Reims fondata nel 1916 con sede nel cuore della città della Champagne. Castelnau produce champagne di stile classico con grande attenzione ai millesimati e ai prestige champagne. Il Brut Réserve e il millesimato Vintage sono le referenze più apprezzate per il loro stile preciso e rifinito.',
 'La Champagne classica di Reims: Castelnau produce champagne di stile elegante e preciso con la lunga tradizione cooperativa della città come base e un''ambizione qualitativa costante.',
 '€€€', false),

-- ── GRANDI MAISON ─────────────────────────────────────────────

('Ayala', 'ayala', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Aÿ', 'Marne', '2 Boulevard du Nord, 51160 Aÿ', '+33 3 26 55 15 44', 'www.champagne-ayala.fr',
 1860, 'Groupe Bollinger', 'Bollinger', NULL, 'Caroline Latrive',
 55, NULL, NULL, 55, 30, 15,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 600000, NULL, 'Pellegrini SpA', true, true,
 'Maison fondata nel 1860 ad Aÿ, oggi di proprietà del gruppo Bollinger. Ayala si è reinventata come casa specialista dei Brut Nature e dei dosaggi bassissimi, con lo Zéro Dosage come cuvée simbolo. Stile preciso, fresco e gastronomico con grande valorizzazione dei Blanc de Blancs. Una delle maison più interessanti per i palati contemporanei.',
 'Il dosaggio zero come manifesto: Ayala ha fatto della precisione e della freschezza la sua identità, producendo champagne extra-brut e brut nature che esprimono il terroir di Aÿ senza mascherature di alcun tipo.',
 '€€€', false),

('Joseph Perrier', 'joseph-perrier', 'NM', NULL,
 'Châlons-en-Champagne', 'Marne', '69 Avenue de Paris, 51016 Châlons-en-Champagne', '+33 3 26 68 29 51', 'www.joseph-perrier.com',
 1825, 'Famille Alain Thiénot', 'Thiénot Group', NULL, NULL,
 NULL, NULL, NULL, 40, 35, 25,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 800000, NULL, NULL, true, true,
 'Storica maison fondata nel 1825 a Châlons-en-Champagne, una delle poche grandi case al di fuori di Épernay e Reims. Joseph Perrier produce champagne di stile classico e grande eleganza, con la Cuvée Royale — già apprezzata dalla Regina Vittoria — come referenza storica principale. Oggi parte del gruppo Thiénot, mantiene la propria identità stilistica intatta.',
 'L''eleganza storica di Châlons: Joseph Perrier porta avanti dal 1825 una tradizione di champagne classici da una città spesso dimenticata nei percorsi enogastronomici, con la Cuvée Royale come simbolo di una storia nobile.',
 '€€€', false),

('Boizel', 'boizel', 'NM', '08daee1e-4c45-4961-9e87-d20c6bac0972',
 'Épernay', 'Marne', '46 Avenue de Champagne, 51200 Épernay', '+33 3 26 55 21 51', 'www.boizel.com',
 1834, 'BCC Group', 'BCC', NULL, NULL,
 NULL, NULL, NULL, 35, 40, 25,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 1200000, NULL, NULL, true, false,
 'Maison storica fondata nel 1834 sull''Avenue de Champagne di Épernay, oggi parte del gruppo BCC. Boizel produce champagne di stile elegante e fresco con grande attenzione ai millesimati e alla Cuvée Joyau de France come prestige champagne di riferimento. Tradizione e modernità si incontrano in una gamma di grande accessibilità.',
 'L''Avenue de Champagne come indirizzo storico: Boizel porta avanti dal 1834 una tradizione di champagne eleganti e precisi, con la Joyau de France come vertice di una gamma destinata alla tavola e al piacere quotidiano.',
 '€€€', false),

('Canard-Duchêne', 'canard-duchene', 'NM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Ludes', 'Marne', 'Rue Edmond Canard, 51500 Ludes', '+33 3 26 61 11 96', 'www.canard-duchene.fr',
 1868, 'Groupe Thiénot', 'Alain Thiénot', NULL, NULL,
 NULL, NULL, NULL, 45, 35, 20,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 4000000, NULL, NULL, true, false,
 'Maison storica fondata nel 1868 a Ludes dalla famiglia Canard, nella Montagne de Reims. Oggi parte del gruppo Alain Thiénot, Canard-Duchêne produce champagne di larga diffusione con uno stile fresco e accessibile. La Léonie e la Cuvée Charles VII sono le referenze principali di una maison con radici profonde nel territorio champenois.',
 'La tradizione di Ludes per tutti: Canard-Duchêne produce champagne di carattere accessibile con 150 anni di storia nella Montagne de Reims, con la Cuvée Charles VII come omaggio alla storia champenoise.',
 '€€', false),

('Paul Bara', 'paul-bara', 'RM', '49ed27e0-9859-431a-ab6c-15a7a6ed13cc',
 'Bouzy', 'Marne', '4 Rue Yvonnet, 51150 Bouzy', '+33 3 26 57 00 50', NULL,
 NULL, 'Famille Bara', 'Indipendente', NULL, NULL,
 11, 11, NULL, 80, 15, 5,
 ARRAY[]::text[], 'pneumatica', 'acciaio inox', 'svolta',
 80000, NULL, NULL, false, true,
 'Vigneron storico di Bouzy, Grand Cru della Montagne de Reims. Paul Bara produce champagne di grande struttura e autenticità da uno dei comuni più celebri per il Pinot Noir. La Comtesse Marie de France, il Grand Rosé Grand Cru e lo Spécial Club millesimato sono le referenze più apprezzate di un domaine che interpreta Bouzy con classe e continuità.',
 'Bouzy Grand Cru nella sua espressione più classica: Paul Bara produce da generazioni champagne di struttura e eleganza che esaltano il potenziale del Pinot Noir in uno dei Grand Crus più vocati della Montagne de Reims.',
 '€€€', false)

ON CONFLICT (slug) DO NOTHING;
